#######
# Compiled from data/ac_lib/functions/crafting.mcscript
# to .//data/ac_lib/functions/crafting/basic/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=minecraft:item,nbt={Item:{id:"minecraft:crafting_table", Count:1b},OnGround:1b}] at @s if entity @e[type=minecraft:item,nbt={Item:{id:"minecraft:iron_block", Count:1b},OnGround:1b},distance=..0.5] run function ac_lib:crafting/basic/convert
