#######
# Compiled from data/ac_lib/scripts_bak/create.mcscript
# to .//data/ac_lib/scripts_bak/create/craftingtable/place.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove aclib_craftingtable_init
playsound minecraft:block.anvil.land block @a ~ ~ ~
setblock ~ ~ ~ minecraft:dropper[facing=down]{CustomName:"{\"text\":\"Advanced Crafting Table\",\"italic\":\"false\"}"} replace