#######
# Compiled from unnamedde/functions/misc/trash_can.mcscript
# to .//data/unnamedde/functions/misc/trash_can/place/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=armor_stand,tag=ud_trash_can_init] at @s if block ~ ~ ~ air run function unnamedde:misc/trash_can/place/place
