#######
# Compiled from unnamedde/functions/misc/trash_can.mcscript
# to .//data/unnamedde/functions/misc/trash_can/place/place.mcfunction
#
# Generated by Minecraft Script for 1.13
######
setblock ~ ~ ~ minecraft:hopper{TransferCooldown:1000000,CustomName:"{\"translate\":\"Trashcan\",\"italic\":\"false\"}"}
tag @s remove ud_trash_can_init
