#######
# Compiled from unnamedde/functions/misc/xp_containers.mcscript
# to .//data/unnamedde/functions/misc/xp_containers/extract_xp.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result score @s ud_temp run data get entity @s SelectedItem.tag.unnamedDE.storedXP
scoreboard players operation @s ud_temp -= @s extract_out_item
execute store result entity @s SelectedItem.tag.unnamedDE.storedXP long 1 run scoreboard players get @s ud_temp
scoreboard players reset @s ud_temp
scoreboard players operation @s ud_temp = @s extract_out_item
function unnamedde:misc/xp_containers/add_xp
scoreboard players reset @s ud_temp
scoreboard players reset @s extract_out_item
