#######
# Compiled from unnamedde/functions/misc/xp_containers.mcscript
# to .//data/unnamedde/functions/misc/xp_containers/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] store result score @s ud_stored_value run data get entity @s SelectedItem.tag.unnamedDE.storedXP
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s ud_xp_points matches 1.. run scoreboard players enable @s store_in_item
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s ud_xp_levels matches 1.. run scoreboard players enable @s store_in_item
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s ud_stored_value matches 1.. run scoreboard players enable @s extract_out_item
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] run scoreboard players enable @s check_item
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s check_item matches 1.. run function unnamedde:misc/xp_containers/check_xp
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s extract_out_item matches 1.. if score @s extract_out_item <= @s ud_stored_value run function unnamedde:misc/xp_containers/extract_xp
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s store_in_item matches 1.. run function unnamedde:misc/xp_containers/store_xp_init
execute as @a at @s unless entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] run scoreboard players reset @s ud_stored_value
