#######
# Compiled from unnamedde/functions/misc/xp_containers.mcscript
# to .//data/unnamedde/functions/misc/xp_containers/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] store result score @s ud_stored_xp run data get entity @s SelectedItem.tag.unnamedDE.storedXP
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s ud_xp matches 1.. run scoreboard players enable @s store_xp
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s ud_stored_xp matches 1.. run scoreboard players enable @s extract_xp
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] run scoreboard players enable @s check_xp
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s store_xp matches 1.. if score @s store_xp <= @s ud_xp run function unnamedde:misc/xp_containers/store_xp
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s extract_xp matches 1.. if score @s extract_xp <= @s ud_stored_xp run function unnamedde:misc/xp_containers/extract_xp
execute as @a at @s if entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s check_xp matches 1.. run function unnamedde:misc/xp_containers/check_xp
execute as @a at @s unless entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s store_xp matches 0 run scoreboard players reset @s store_xp
execute as @a at @s unless entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s extract_xp matches 0 run scoreboard players reset @s extract_xp
execute as @a at @s unless entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] if score @s check_xp matches 0 run scoreboard players reset @s check_xp
execute as @a at @s unless entity @s[nbt={SelectedItem:{Count:1b,tag:{unnamedDE:{id:"xp_container"}}}}] run scoreboard players reset @s ud_stored_xp
