#######
# Compiled from unnamedde/functions/misc/xp_containers.mcscript
# to .//data/unnamedde/functions/misc/xp_containers/store_xp_init.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players add @s ud_temp 1
function unnamedde:misc/xp_containers/store_xp
