#######
# Compiled from unnamedde/functions/misc/xp_containers.mcscript
# to .//data/unnamedde/functions/misc/xp_containers/store_xp.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s ud_xp_points matches 1.. if score @s ud_temp < @s store_xp run function unnamedde:misc/xp_containers/remove_xp
execute if score @s ud_xp_levels matches 1.. if score @s ud_temp < @s store_xp run function unnamedde:misc/xp_containers/remove_xp
execute if score @s ud_xp_points matches 1.. unless score @s ud_temp < @s store_xp run function unnamedde:misc/xp_containers/store_xp_finish
execute if score @s ud_xp_levels matches 1.. unless score @s ud_temp < @s store_xp run function unnamedde:misc/xp_containers/store_xp_finish
execute unless score @s ud_xp_points matches 1.. run function unnamedde:misc/xp_containers/store_xp_finish
execute unless score @s ud_xp_levels matches 1.. run function unnamedde:misc/xp_containers/store_xp_finish
scoreboard players reset @s store_in_item
