#######
# Compiled from unnamedde/functions/misc/xp_containers.mcscript
# to .//data/unnamedde/functions/misc/xp_containers/store_xp_finish.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result score @s ud_temp2 run data get entity @s SelectedItem.tag.unnamedDE.storedXP
scoreboard players operation @s ud_temp += @s ud_temp2
execute store result entity @s SelectedItem.tag.unnamedDE.storedXP long 1 run scoreboard players get @s ud_temp
scoreboard players reset @s ud_temp
scoreboard players reset @s ud_temp2
