#######
# Compiled from data/ac_lib/scripts_bak/create.mcscript
# to .//data/ac_lib/scripts_bak/create/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:create/craftingtable/detect
