#######
# Compiled from unnamedde/functions/misc/parcour_boots.mcscript
# to .//data/unnamedde/functions/misc/parcour_boots/crouch/deactivate.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove ud_parcour_crouch
tp @e[type=shulker,tag=ud_parcour_crouch_shulker,limit=1,sort=nearest,distance=...5] ~ -500 ~