#######
# Compiled from data/unnamedde/functions/set_scoreboards.mcscript
# to .//data/unnamedde/functions/set_scoreboards/on_death.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players reset @s ud_deathtime_m
scoreboard players reset @s ud_deathtime_h