#######
# Compiled from data/unnamedde/functions/set_scoreboards.mcscript
# to .//data/unnamedde/functions/set_scoreboards/on_join.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function #unnamedde:on_join
scoreboard players reset @s ud_leave