#######
# Compiled from data/unnamedde/functions/set_scoreboards.mcscript
# to .//data/unnamedde/functions/set_scoreboards/player.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result score @s x_pos run data get entity @s Pos[0]
execute store result score @s y_pos run data get entity @s Pos[1]
execute store result score @s z_pos run data get entity @s Pos[2]
execute store result score @s x_rot run data get entity @s Rotation[0]
execute store result score @s y_rot run data get entity @s Rotation[1]
execute unless score @s ud_deathtime_m matches 0.. run scoreboard players add @s ud_deathtime_m 0

execute unless score @s ud_deathtime_h matches 0.. run scoreboard players add @s ud_deathtime_h 0

execute unless score @s ud_timeplayed_m matches 0.. run scoreboard players add @s ud_timeplayed_m 0

execute unless score @s ud_timeplayed_h matches 0.. run scoreboard players add @s ud_timeplayed_h 0

execute if score @s ud_deathtime matches 1200.. run scoreboard players add @s ud_deathtime_m 1
execute if score @s ud_deathtime matches 1200.. run scoreboard players remove @s ud_deathtime 1200
execute if score @s ud_deathtime matches 1200.. run function unnamedde:misc/tooltips/set_scoreboards

execute if score @s ud_deathtime_m matches 60.. run scoreboard players add @s ud_deathtime_h 1
execute if score @s ud_deathtime_m matches 60.. run scoreboard players remove @s ud_deathtime_m 60
execute if score @s ud_deathtime_m matches 60.. run function unnamedde:misc/tooltips/set_scoreboards

execute if score @s ud_timeplayed matches 1200.. run scoreboard players add @s ud_timeplayed_m 1
execute if score @s ud_timeplayed matches 1200.. run scoreboard players remove @s ud_timeplayed 1200
execute if score @s ud_timeplayed matches 1200.. run function unnamedde:misc/tooltips/set_scoreboards

execute if score @s ud_timeplayed_m matches 60.. run scoreboard players add @s ud_timeplayed_h 1
execute if score @s ud_timeplayed_m matches 60.. run scoreboard players remove @s ud_timeplayed_m 60
execute if score @s ud_timeplayed_m matches 60.. run function unnamedde:misc/tooltips/set_scoreboards

