#######
# Compiled from data/unnamedde/functions/set_scoreboards.mcscript
# to .//data/unnamedde/functions/set_scoreboards/player.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result score @s ud_arrowcount run clear @s minecraft:arrow 0
execute store result score @s ud_temp run clear @s minecraft:tipped_arrow 0
scoreboard players operation @s ud_arrowcount += @s ud_temp
execute store result score @s ud_temp run clear @s minecraft:spectral_arrow 0
scoreboard players operation @s ud_arrowcount += @s ud_temp
scoreboard players reset @s ud_temp
execute store result score @s ud_torchcount run clear @s minecraft:torch 0