#######
# Compiled from data/unnamedde/functions/set_scoreboards.mcscript
# to .//data/unnamedde/functions/set_scoreboards/reset.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players reset @a[scores={ud_mine_quartz=1..}] ud_mine_quartz
scoreboard players reset @a[scores={ud_eat_pork_c=1..}] ud_eat_pork_c
scoreboard players reset @a[scores={ud_eat_pork_r=1..}] ud_eat_pork_r
scoreboard players reset @a[scores={ud_p_endcrystal=1..}] ud_p_endcrystal
