#######
# Compiled from data/unnamedde/functions/set_scoreboards.mcscript
# to .//data/unnamedde/functions/set_scoreboards/reset_item_interactives.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a if score @s store_in_item matches 0 run scoreboard players reset @s store_in_item
execute as @a if score @s extract_out_item matches 0 run scoreboard players reset @s extract_out_item
execute as @a if score @s check_item matches 0 run scoreboard players reset @s check_item
