#######
# Compiled from data/unnamedde/functions/set_scoreboards.mcscript
# to .//data/unnamedde/functions/set_scoreboards/world.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result score daytime ud_misc run time query daytime
execute store result score day ud_misc run time query day
scoreboard players operation real_daytime ud_misc = daytime ud_misc
scoreboard players add real_daytime ud_misc 6000
execute if score real_daytime ud_misc matches 24000.. run scoreboard players remove real_daytime ud_misc 24000

scoreboard players operation real_daytime% ud_misc = real_daytime ud_misc
scoreboard players operation real_daytime% ud_misc /= 240 ud_const
scoreboard players operation real_day ud_misc = day ud_misc
scoreboard players add real_day ud_misc 1
