#######
# Compiled from unnamedde/functions/misc/ender_beacons.mcscript
# to .//data/unnamedde/functions/misc/ender_beacons/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=item_frame,nbt={Item:{id:"minecraft:dragon_egg"}}] at @s if entity @e[type=item,nbt={Item:{id:"minecraft:dragon_breath",Count:8b},OnGround:1b},distance=...75] run function unnamedde:misc/ender_beacons/create
