#######
# Compiled from unnamedde/functions/misc/ender_beacons.mcscript
# to .//data/unnamedde/functions/misc/ender_beacons/second.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[nbt={EnderItems:[{tag:{unnamedDE:{id:"ender_beacon"}}}]}] at @s run function unnamedde:misc/ender_beacons/give_effects
