#######
# Compiled from unnamedde/functions/misc/deaths.mcscript
# to .//data/unnamedde/functions/misc/deaths/after_death.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove is_dead
scoreboard players reset @s ud_deaths
function #unnamedde:after_death
