#######
# Compiled from unnamedde/functions/misc/deaths.mcscript
# to .//data/unnamedde/functions/misc/deaths/death_sound.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score deaths ud_options matches 1.. run playsound minecraft:entity.wolf.howl ambient @s

