#######
# Compiled from unnamedde/functions/misc/ender_hoppers.mcscript
# to .//data/unnamedde/functions/misc/ender_hoppers/collect_item.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if data block ~ ~ ~ Items[{Slot:0b}] if data block ~ ~ ~ Items[{Slot:1b}] if data block ~ ~ ~ Items[{Slot:2b}] if data block ~ ~ ~ Items[{Slot:3b}] unless data block ~ ~ ~ Items[{Slot:4b}] run function unnamedde:misc/ender_hoppers/insert_item/4
execute if data block ~ ~ ~ Items[{Slot:0b}] if data block ~ ~ ~ Items[{Slot:1b}] if data block ~ ~ ~ Items[{Slot:2b}] unless data block ~ ~ ~ Items[{Slot:3b}] run function unnamedde:misc/ender_hoppers/insert_item/3
execute if data block ~ ~ ~ Items[{Slot:0b}] if data block ~ ~ ~ Items[{Slot:1b}] unless data block ~ ~ ~ Items[{Slot:2b}] run function unnamedde:misc/ender_hoppers/insert_item/2
execute if data block ~ ~ ~ Items[{Slot:0b}] unless data block ~ ~ ~ Items[{Slot:1b}] run function unnamedde:misc/ender_hoppers/insert_item/1
execute unless data block ~ ~ ~ Items[{Slot:0b}] run function unnamedde:misc/ender_hoppers/insert_item/0
kill @s[type=item]

