#######
# Compiled from data/smash_lib/functions/action.mcscript
# to .//data/smash_lib/functions/action/anvil.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set @s smash_anvil_cool 50
scoreboard players remove @s smash_anvil 1
