#######
# Compiled from data/smash_lib/functions/action.mcscript
# to .//data/smash_lib/functions/action/clear.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[scores={smash_anvil=0}] run scoreboard players reset @s smash_anvil

execute as @e[scores={smash_anvil_cool=0}] run scoreboard players reset @s smash_anvil_cool


execute as @e[scores={smash_piston=0}] run scoreboard players reset @s smash_piston

execute as @e[scores={smash_pston_cool=0}] run scoreboard players reset @s smash_pston_cool
