#######
# Compiled from data/smash_lib/functions/action.mcscript
# to .//data/smash_lib/functions/action/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function smash_lib:action/clear

execute as @e[scores={smash_anvil=1..}] at @s run function smash_lib:action/anvil

scoreboard players remove @e[scores={smash_anvil_cool=1..}] smash_anvil_cool 1

tag @e[scores={smash_anvil_cool=49}] add smash_anvil
tag @e[tag=smash_anvil,scores={smash_anvil_cool=..48}] remove smash_anvil




execute as @e[scores={smash_piston=1..}] at @s run function smash_lib:action/piston

scoreboard players remove @e[scores={smash_pston_cool=1..}] smash_pston_cool 1

tag @e[scores={smash_pston_cool=49}] add smash_piston
tag @e[tag=smash_piston,scores={smash_pston_cool=..48}] remove smash_piston
