#######
# Compiled from data/smash_lib/functions/action.mcscript
# to .//data/smash_lib/functions/action/piston.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set @s smash_pston_cool 50
scoreboard players remove @s smash_piston 1