#######
# Compiled from unnamedde/functions/misc/encrypted_books.mcscript
# to .//data/unnamedde/functions/misc/encrypted_books/encrypt/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:written_book{unnamedDE:{Encrypted:1}} 1
data modify block ~ ~ ~ Items[{Slot:16b}].tag.unnamedDE.encrypted.pages set from block ~ ~ ~ Items[{Slot:1b}].tag.pages
data modify block ~ ~ ~ Items[{Slot:16b}].tag.unnamedDE.encrypted.title set from block ~ ~ ~ Items[{Slot:1b}].tag.title
data modify block ~ ~ ~ Items[{Slot:16b}].tag.unnamedDE.encrypted.author set from block ~ ~ ~ Items[{Slot:1b}].tag.author
data modify block ~ ~ ~ Items[{Slot:16b}].tag.unnamedDE.encrypted.key set from block ~ ~ ~ Items[{Slot:2b}].tag.display.Name
data modify block ~ ~ ~ Items[{Slot:16b}].tag.pages set value ['{"text":""}']
data modify block ~ ~ ~ Items[{Slot:16b}].tag.title set value "Written Book"
data modify block ~ ~ ~ Items[{Slot:16b}].tag.author set from block ~ ~ ~ Items[{Slot:1b}].tag.author
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_encrypt_book
