#######
# Compiled from unnamedde/functions/misc/tooltips.mcscript
# to .//data/unnamedde/functions/misc/tooltips/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[tag=ud_tooltip_elytra] unless entity @s[gamemode=!spectator,nbt={FallFlying:1b,Inventory:[{Slot:102b,id:"minecraft:elytra"},{id:"minecraft:compass"}]}] run title @s actionbar ""
execute as @a[tag=ud_tooltip_compass] unless entity @s[gamemode=!spectator,nbt={SelectedItem:{id:"minecraft:compass"}}] run title @s actionbar ""
execute as @a[tag=ud_tooltip_clock] unless entity @s[gamemode=!spectator,nbt={SelectedItem:{id:"minecraft:clock"}}] run title @s actionbar ""
execute as @a[tag=ud_tooltip_death_book] unless entity @s[gamemode=!spectator,nbt={SelectedItem:{tag:{unnamedDE:{id:"death_book"}}}}] run title @s actionbar ""
execute as @a[tag=ud_tooltip_bow] unless entity @s[gamemode=!spectator,nbt={SelectedItem:{id:"minecraft:bow"}}] unless entity @s[gamemode=!spectator,nbt={SelectedItem:{id:"minecraft:crossbow"}}] run title @s actionbar ""
execute as @a[tag=ud_tooltip_torch] unless entity @s[gamemode=!spectator,nbt={SelectedItem:{id:"minecraft:torch"}}] run title @s actionbar ""
execute as @a[gamemode=!spectator] at @s if entity @s[nbt={FallFlying:1b,Inventory:[{Slot:102b,id:"minecraft:elytra"},{id:"minecraft:compass"}]}] unless entity @s[nbt={SelectedItem:{id:"minecraft:torch"}}] unless entity @s[nbt={SelectedItem:{id:"minecraft:bow"}}] unless entity @s[nbt={SelectedItem:{id:"minecraft:crossbow"}}] unless entity @s[nbt={SelectedItem:{id:"minecraft:clock"}}] unless entity @s[nbt={SelectedItem:{tag:{unnamedDE:{id:"death_book"}}}}] run function unnamedde:misc/tooltips/display/elytra
execute as @a[gamemode=!spectator] at @s unless entity @s[nbt={FallFlying:1b,Inventory:[{Slot:102b,id:"minecraft:elytra"},{id:"minecraft:compass"}]}] run tag @s remove ud_tooltip_elytra
execute as @a[gamemode=!spectator] at @s if entity @s[nbt={SelectedItem:{id:"minecraft:compass"}}] run function unnamedde:misc/tooltips/display/compass
execute as @a[gamemode=!spectator] at @s unless entity @s[nbt={SelectedItem:{id:"minecraft:compass"}}] run tag @s remove ud_tooltip_compass
execute as @a[gamemode=!spectator] at @s if entity @s[nbt={SelectedItem:{id:"minecraft:clock"}}] run function unnamedde:misc/tooltips/display/clock
execute as @a[gamemode=!spectator] at @s unless entity @s[nbt={SelectedItem:{id:"minecraft:clock"}}] run tag @s remove ud_tooltip_clock
execute as @a[gamemode=!spectator] at @s if entity @s[nbt={SelectedItem:{tag:{unnamedDE:{id:"death_book"}}}}] run function unnamedde:misc/tooltips/display/death_book
execute as @a[gamemode=!spectator] at @s unless entity @s[nbt={SelectedItem:{tag:{unnamedDE:{id:"death_book"}}}}] run tag @s remove ud_tooltip_death_book
execute as @a[gamemode=!spectator] at @s if entity @s[nbt={SelectedItem:{id:"minecraft:bow"}}] run function unnamedde:misc/tooltips/display/bow
execute as @a[gamemode=!spectator] at @s if entity @s[nbt={SelectedItem:{id:"minecraft:crossbow"}}] run function unnamedde:misc/tooltips/display/bow
execute as @a[gamemode=!spectator] at @s unless entity @s[nbt={SelectedItem:{id:"minecraft:bow"}}] unless entity @s[nbt={SelectedItem:{id:"minecraft:crossbow"}}] run tag @s remove ud_tooltip_bow
execute as @a[gamemode=!spectator] at @s if entity @s[nbt={SelectedItem:{id:"minecraft:torch"}}] run function unnamedde:misc/tooltips/display/torch
execute as @a[gamemode=!spectator] at @s unless entity @s[nbt={SelectedItem:{id:"minecraft:torch"}}] run tag @s remove ud_tooltip_torch
execute as @a[gamemode=!spectator] at @s if entity @s[tag=!ud_tooltip_clock_notify,nbt={Dimension:0b,Inventory:[{id:"minecraft:clock"}]}] if score daytime ud_misc matches 13000.. run function unnamedde:misc/tooltips/notify/clock
execute as @a[gamemode=!spectator] at @s unless score daytime ud_misc matches 13000.. if entity @s[tag=ud_tooltip_clock_notify] run advancement revoke @s only unnamedde:notify/nighttime
execute as @a[gamemode=!spectator] at @s unless score daytime ud_misc matches 13000.. if entity @s[tag=ud_tooltip_clock_notify] run tag @s remove ud_tooltip_clock_notify
