#######
# Compiled from unnamedde/functions/misc/tooltips.mcscript
# to .//data/unnamedde/functions/misc/tooltips/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[tag=ud_tooltip_compass] unless entity @s[nbt={SelectedItem:{id:"minecraft:compass"}}] run title @s actionbar ""
execute as @a[tag=ud_tooltip_clock] unless entity @s[nbt={SelectedItem:{id:"minecraft:clock"}}] run title @s actionbar ""
execute as @a[tag=ud_tooltip_bone] unless entity @s[nbt={SelectedItem:{id:"minecraft:bone"}}] run title @s actionbar ""
execute as @a at @s if entity @s[nbt={SelectedItem:{id:"minecraft:compass"}}] run function unnamedde:misc/tooltips/display/compass
execute as @a at @s unless entity @s[nbt={SelectedItem:{id:"minecraft:compass"}}] run tag @s remove ud_tooltip_compass
execute as @a at @s if entity @s[nbt={SelectedItem:{id:"minecraft:clock"}}] run function unnamedde:misc/tooltips/display/clock
execute as @a at @s unless entity @s[nbt={SelectedItem:{id:"minecraft:clock"}}] run tag @s remove ud_tooltip_clock
execute as @a at @s if entity @s[nbt={SelectedItem:{id:"minecraft:bone"}}] run function unnamedde:misc/tooltips/display/bone
execute as @a at @s unless entity @s[nbt={SelectedItem:{id:"minecraft:bone"}}] run tag @s remove ud_tooltip_bone
execute as @a at @s if entity @s[tag=!ud_tooltip_clock_notify,nbt={Inventory:[{id:"minecraft:clock"}]}] if score daytime ud_misc matches 13000.. run function unnamedde:misc/tooltips/notify/clock
execute as @a at @s unless score daytime ud_misc matches 13000.. if entity @s[tag=ud_tooltip_clock_notify] run advancement revoke @s only unnamedde:notify/nighttime
execute as @a at @s unless score daytime ud_misc matches 13000.. if entity @s[tag=ud_tooltip_clock_notify] run tag @s remove ud_tooltip_clock_notify
