#######
# Compiled from unnamedde/functions/misc/better_endportal.mcscript
# to .//data/unnamedde/functions/misc/better_endportal/killed_dragon.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function unnamedde:misc/better_endportal/repair_portal