#######
# Compiled from unnamedde/functions/misc/better_endportal.mcscript
# to .//data/unnamedde/functions/misc/better_endportal/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[nbt={Dimension:1},scores={ud_p_endcrystal=1..}] at @s run schedule function unnamedde:misc/better_endportal/repair_portal 3s
