#######
# Compiled from unnamedde/functions/misc/encrypted_books.mcscript
# to .//data/unnamedde/functions/misc/encrypted_books/decrypt/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if data block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.key run data modify block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.key_test set from block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.key
execute if data block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.key store success score @s ud_temp run data modify block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.key_test set from block ~ ~ ~ Items[{Slot:2b}].tag.display.Name
execute if data block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.key if score @s ud_temp matches 0 run function unnamedde:misc/encrypted_books/decrypt/decrypt

scoreboard players reset @s ud_temp
