#######
# Compiled from data/unnamedde/functions/creative_menu.mcscript
# to .//data/unnamedde/functions/creative_menu.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s {"text":""}
tellraw @s {"text":""}
tellraw @s [{"text":"<===== ","color":"aqua"},{"text":"Select datapack to display menu","color":"red"},{"text":" =====>","color":"aqua"}]
tellraw @s {"text":""}
function #unnamedde:creative_menu
tellraw @s {"text":""}
tellraw @s {"text":""}
