#######
# Compiled from data/unnamedde/functions/management.mcscript
# to .//data/unnamedde/functions/datapack_list_init.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score datapack_list datapack_list matches 1.. run scoreboard players set unnamedde datapack_list 1