#######
# Compiled from data/unnamedde/functions/load.mcscript
# to .//data/unnamedde/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function unnamedde:mcscript/load

scoreboard objectives add ud_creative_menu dummy
scoreboard objectives add death_x dummy "X-Position at Death"
scoreboard objectives add death_y dummy "Y-Position at Death"
scoreboard objectives add death_z dummy "Z-Position at Death"
scoreboard objectives add ud_arrowcount dummy
scoreboard objectives add ud_torchcount dummy
scoreboard objectives add store_in_item trigger "Store value into container"
scoreboard objectives add extract_out_item trigger "Extract value from container"
scoreboard objectives add check_item trigger "Check value from container"
scoreboard objectives add ud_stored_value dummy
scoreboard objectives add set_frequency trigger "Set Wireless-Redstone Frequency"
scoreboard objectives add ud_mine_quartz minecraft.mined:minecraft.nether_quartz_ore "Mined Quartz Ore"
scoreboard objectives add ud_eat_pork_r minecraft.used:minecraft.porkchop "Eat Porkchop"
scoreboard objectives add ud_eat_pork_c minecraft.used:minecraft.cooked_porkchop "Eat Cooked Porkchop"
scoreboard objectives add ud_crossbow minecraft.used:minecraft.crossbow "Shoot Crossbow"
scoreboard objectives add ud_p_endcrystal minecraft.used:minecraft.end_crystal "Placed end crystal"
scoreboard objectives add check_drawer trigger "Check item of a drawer"
team add nopvp "No PvP"
execute unless score command_feedback ud_options matches -1.. run scoreboard players set command_feedback ud_options 0

execute unless score greeting ud_options matches -1.. run scoreboard players set greeting ud_options 1

execute unless score concrete_in_water ud_options matches -1.. run scoreboard players set concrete_in_water ud_options 1

execute unless score death_books ud_options matches -1.. run scoreboard players set death_books ud_options 1

execute unless score greeting ud_options matches -1.. run scoreboard players set greeting ud_options 1

execute unless score start_equip ud_options matches -1.. run scoreboard players set start_equip ud_options 0

execute unless score hopper_minecarts ud_options matches -1.. run scoreboard players set hopper_minecarts ud_options 1

execute unless score nightpvp ud_options matches -1.. run scoreboard players set nightpvp ud_options 1

execute unless score silencer ud_options matches -1.. run scoreboard players set silencer ud_options 1

execute unless score tooltips ud_options matches -1.. run scoreboard players set tooltips ud_options 1

execute unless score replant_saplings ud_options matches -1.. run scoreboard players set replant_saplings ud_options 1

execute unless score dispenser_plant ud_options matches -1.. run scoreboard players set dispenser_plant ud_options 1

execute unless score no_too_expensive ud_options matches -1.. run scoreboard players set no_too_expensive ud_options 0

execute unless score xp_containers ud_options matches -1.. run scoreboard players set xp_containers ud_options 1

execute unless score ender_hoppers ud_options matches -1.. run scoreboard players set ender_hoppers ud_options 1

execute unless score plated_elytras ud_options matches -1.. run scoreboard players set plated_elytras ud_options 1

execute unless score bonsai_pots ud_options matches -1.. run scoreboard players set bonsai_pots ud_options 1

execute unless score wireless_redstone ud_options matches -1.. run scoreboard players set wireless_redstone ud_options 1

execute unless score possessive_pigmen ud_options matches -1.. run scoreboard players set possessive_pigmen ud_options 1

execute unless score graves ud_options matches -1.. run scoreboard players set graves ud_options 1

execute unless score player_heads ud_options matches -1.. run scoreboard players set player_heads ud_options 1

execute unless score dragon_egg ud_options matches -1.. run scoreboard players set dragon_egg ud_options 1

execute unless score magnifying_glass ud_options matches -1.. run scoreboard players set magnifying_glass ud_options 1

execute unless score dimension_notifications ud_options matches -1.. run scoreboard players set dimension_notifications ud_options 1

execute unless score arrow_break_bamboo ud_options matches -1.. run scoreboard players set arrow_break_bamboo ud_options 1

execute unless score better_end_portal ud_options matches -1.. run scoreboard players set better_end_portal ud_options 1

execute unless score parcour_boots ud_options matches -1.. run scoreboard players set parcour_boots ud_options 0

execute unless score ender_beacons ud_options matches -1.. run scoreboard players set ender_beacons ud_options 1

execute unless score crossbow_bolts ud_options matches -1.. run scoreboard players set crossbow_bolts ud_options 1

execute unless score storage_drawers ud_options matches -1.. run scoreboard players set storage_drawers ud_options 1

execute unless score trash_can ud_options matches -1.. run scoreboard players set trash_can ud_options 1

execute unless score encrypted_books ud_options matches -1.. run scoreboard players set encrypted_books ud_options 1

execute unless score money_additions ud_options matches -1.. run scoreboard players set money_additions ud_options 1

execute unless score functional_stonecutter ud_options matches -1.. run scoreboard players set functional_stonecutter ud_options 1

execute unless score dispenser_planting ud_options matches -1.. run scoreboard players set dispenser_planting ud_options 1

execute unless score bonsai_pots_cool ud_options matches -1.. run scoreboard players set bonsai_pots_cool ud_options 18000

execute unless score grave_mode ud_options matches -1.. run scoreboard players set grave_mode ud_options 1

team modify nopvp friendlyFire true