#######
# Compiled from data/unnamedde/functions/main.mcscript
# to .//data/unnamedde/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result score daytime ud_misc run time query daytime
execute store result score day ud_misc run time query day
execute as @r[tag=!ud_id_set] at @s run function unnamedde:player_id/first_join
execute as @a[scores={ud_leave=1..}] run scoreboard players reset @s ud_leave
function unnamedde:set_scoreboards/world
execute as @a at @s run function unnamedde:set_scoreboards/player
function unnamedde:creative_menu/main
function unnamedde:player_id/main
function unnamedde:misc/deaths/main
execute if score money ud_options matches 1.. run function unnamedde:money/main

execute if score hopper_minecarts ud_options matches 1.. run function unnamedde:misc/hopper_minecarts

execute if score concrete_in_water ud_options matches 1.. run function unnamedde:misc/concrete_in_water

execute if score nightpvp ud_options matches 1.. run function unnamedde:misc/nightpvp/main

execute if score tooltips ud_options matches 1.. run function unnamedde:misc/tooltips/main

execute if score silencer ud_options matches 1.. run function unnamedde:misc/silencer/main

execute if score replant_saplings ud_options matches 1.. run function unnamedde:misc/replant_saplings/main
