#######
# Compiled from data/unnamedde/functions/second.mcscript
# to .//data/unnamedde/functions/second.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score ender_beacons ud_options matches 1.. run function unnamedde:misc/ender_beacons/second
