#######
# Compiled from data/unnamedde/functions/management.mcscript
# to .//data/unnamedde/functions/uninstall.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard objectives remove smash_anvil
scoreboard objectives remove smash_anvil_cool
scoreboard objectives remove smash_piston
scoreboard objectives remove smash_p_cool
scoreboard objectives add installed_packs
scoreboard objectives add ud_const
scoreboard objectives add money
scoreboard objectives add pay_money
scoreboard objectives add check_money
scoreboard objectives add player_id
scoreboard objectives add group_id
scoreboard objectives add invite_id
scoreboard objectives add invite_player
scoreboard objectives add accept_invite
scoreboard objectives add leave_group
scoreboard objectives add kick_player
scoreboard objectives add ud_creative_menu
scoreboard objectives add ud_misc
scoreboard objectives add ud_counter
scoreboard objectives add ud_leave
scoreboard objectives add x_pos
scoreboard objectives add y_pos
scoreboard objectives add z_pos
scoreboard objectives add death_x
scoreboard objectives add death_y
scoreboard objectives add death_z
scoreboard objectives add x_rot
scoreboard objectives add y_rot
scoreboard objectives add deaths
scoreboard objectives add ud_deaths deathCount
scoreboard objectives add ud_deathtime minecraft.custom:minecraft.time_since_death
scoreboard objectives add ud_timeplayed minecraft.custom:minecraft.play_one_minute
scoreboard objectives add ud_deathtime_h
scoreboard objectives add ud_deathtime_m
scoreboard objectives add ud_timeplayed_h
scoreboard objectives add ud_timeplayed_m
team remove nopvp