#######
# Compiled from unnamedde/functions/misc/plated_elytras.mcscript
# to .//data/unnamedde/functions/misc/plated_elytras/craft/unbreakable/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:elytra 1
data modify block ~ ~ ~ Items[{Slot:16b}].tag set from block ~ ~ ~ Items[{Slot:1b}].tag
data modify block ~ ~ ~ Items[{Slot:16b}].tag.Unbreakable set value 1
data modify block ~ ~ ~ Items[{Slot:16b}].tag.unnamedDE.platedElytras.Unbreakable set value 1
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_unbreakable_elytra
