#######
# Compiled from unnamedde/functions/misc/crossbow_bolts.mcscript
# to .//data/unnamedde/functions/misc/crossbow_bolts/craft/thunderbolt/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:arrow{display:{Name:"{\"text\":\"Thunder-Bolt\",\"italic\":false}",Lore:["{\"text\":\"A lightning bolt will strike where it lands\",\"color\":\"green\",\"italic\":false}","{\"text\":\"When used with a bow it acts like a normal arrow\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701002,unnamedDE:{IsBolt:1,id:"thunderbolt"}} 4
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_thunderbolt
