#######
# Compiled from unnamedde/functions/misc/crossbow_bolts.mcscript
# to .//data/unnamedde/functions/misc/crossbow_bolts/craft/thunderbolt/3.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.7 minecraft:air
replaceitem block ~ ~ ~ container.16 minecraft:air
replaceitem block ~ ~ ~ container.25 minecraft:air
tag @s remove ac_lib_advanced_crafter_crafted
tag @s remove ac_lib_advanced_crafter_crafted_thunderbolt