#######
# Compiled from data/ac_lib/functions/remove.mcscript
# to .//data/ac_lib/functions/remove/craftingtable/remove.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tp @s ~ -500 ~
execute as @e[type=minecraft:item,nbt={Item:{id:"minecraft:dropper",Count:1b}},distance=..1,limit=1,sort=nearest] at @s run data merge entity @s {Item:{id:"minecraft:armor_stand",Count:1b,tag:{CustomModelData:702001,display:{Name:"{\"text\":\"Advanced Crafing Table\",\"color\":\"yellow\",\"italic\":\"false\"}",Lore:["{\"text\":\"Right-click to place\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}],EntityTag:{Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["aclib_craftingtable","aclib_craftingtable_init"],DisabledSlots:4144959}}}}