#######
# Compiled from data/ac_lib/functions/crafting.mcscript
# to .//data/ac_lib/functions/crafting/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:crafting/basic/detect
