#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/place/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=armor_stand,tag=ac_lib_advanced_crafter_init] at @s if block ~ ~ ~ air run function ac_lib:advanced_crafter/place/place
