#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/place/place.mcfunction
#
# Generated by Minecraft Script for 1.13
######
setblock ~ ~ ~ minecraft:gray_shulker_box{CustomName:"{\"text\":\"Advanced Crafting Table\",\"italic\":\"false\"}"}
tag @s remove ac_lib_advanced_crafter_init
