#######
# Compiled from unnamedde/functions/misc/wireless_redstone.mcscript
# to .//data/unnamedde/functions/misc/wireless_redstone/craft/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Wireless Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Put in a item frame next to a\",\"color\":\"green\",\"italic\":false}","{\"text\":\"redstone block\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701003,unnamedDE:{id:"wireless_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 2
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_wireless_upgrade
