#######
# Compiled from unnamedde/functions/misc/magnifying_glass.mcscript
# to .//data/unnamedde/functions/misc/magnifying_glass/activate.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s[tag=!ud_magnified] add ud_magnified
effect give @s minecraft:slowness 1 9 true
