#######
# Compiled from unnamedde/functions/misc/magnifying_glass.mcscript
# to .//data/unnamedde/functions/misc/magnifying_glass/deactivate.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s[tag=ud_magnified] remove ud_magnified
effect clear @s minecraft:slowness
