#######
# Compiled from unnamedde/functions/misc/magnifying_glass.mcscript
# to .//data/unnamedde/functions/misc/magnifying_glass/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[nbt={SelectedItem:{tag:{unnamedDE:{id:"magnifying_glass"}}}}] at @s unless data entity @s ActiveEffects[{Id:2b,ShowParticles:1b}] run function unnamedde:misc/magnifying_glass/activate
execute as @a[tag=ud_magnified,nbt=!{SelectedItem:{tag:{unnamedDE:{id:"magnifying_glass"}}}}] at @s run function unnamedde:misc/magnifying_glass/deactivate
