#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/recipes/test/2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:advanced_crafter/crafted
tag @s remove ac_lib_advanced_crafter_crafted
tag @s remove ac_lib_advanced_crafter_crafted_test
