#######
# Compiled from unnamedde/functions/misc/magnifying_glass.mcscript
# to .//data/unnamedde/functions/misc/magnifying_glass/craft/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Magnifying glass\",\"italic\":false}",Lore:["{\"text\":\"Hold to zoom in\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701004,unnamedDE:{id:"magnifying_glass",NoPlacing:1}} 1
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_magnifying_glass
