#######
# Compiled from unnamedde/functions/misc/magnifying_glass.mcscript
# to .//data/unnamedde/functions/misc/magnifying_glass/craft/2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:advanced_crafter/crafted
tag @s remove ac_lib_advanced_crafter_crafted
tag @s remove ac_lib_advanced_crafter_crafted_magnifying_glass
