#######
# Compiled from unnamedde/functions/misc/money_additions.mcscript
# to .//data/unnamedde/functions/misc/money_additions/craft/wallet/3.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:air
tag @s remove ac_lib_advanced_crafter_crafted
tag @s remove ac_lib_advanced_crafter_crafted_wallet
