#######
# Compiled from unnamedde/functions/misc/dispenser_plant.mcscript
# to .//data/unnamedde/functions/misc/dispenser_plant/plant_full.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[nbt={Item:{id:"minecraft:oak_sapling"}}] if block ~ ~ ~ minecraft:air if block ~ ~-1 ~ #unnamedde:tree_plantable run tag @s add ud_dispenser_replant_oak

execute if entity @s[nbt={Item:{id:"minecraft:spruce_sapling"}}] if block ~ ~ ~ minecraft:air if block ~ ~-1 ~ #unnamedde:tree_plantable run tag @s add ud_dispenser_replant_spruce

execute if entity @s[nbt={Item:{id:"minecraft:birch_sapling"}}] if block ~ ~ ~ minecraft:air if block ~ ~-1 ~ #unnamedde:tree_plantable run tag @s add ud_dispenser_replant_birch

execute if entity @s[nbt={Item:{id:"minecraft:jungle_sapling"}}] if block ~ ~ ~ minecraft:air if block ~ ~-1 ~ #unnamedde:tree_plantable run tag @s add ud_dispenser_replant_jungle

execute if entity @s[nbt={Item:{id:"minecraft:acacia_sapling"}}] if block ~ ~ ~ minecraft:air if block ~ ~-1 ~ #unnamedde:tree_plantable run tag @s add ud_dispenser_replant_acacia

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_sapling"}}] if block ~ ~ ~ minecraft:air if block ~ ~-1 ~ #unnamedde:tree_plantable run tag @s add ud_dispenser_replant_dark_oak

execute if entity @s[nbt={Item:{id:"minecraft:chorus_flower"}}] if block ~ ~ ~ minecraft:air if block ~ ~-1 ~ minecraft:end_stone run tag @s add ud_dispenser_replant_chorus

execute if entity @s[nbt={Item:{id:"minecraft:nether_wart"}}] if block ~ ~ ~ minecraft:air if block ~ ~-1 ~ minecraft:soul_sand run tag @s add ud_dispenser_replant_wart

execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}}] if block ~ ~ ~ minecraft:air run tag @s add ud_dispenser_replant_cocoa

execute if entity @s[nbt={Item:{id:"minecraft:oak_sapling"}},tag=ud_dispenser_replant_oak] if block ~ ~ ~ minecraft:air run setblock ~ ~ ~ minecraft:oak_sapling
execute if entity @s[nbt={Item:{id:"minecraft:oak_sapling"}},tag=ud_dispenser_replant_oak] if block ~ ~ ~ minecraft:oak_sapling run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:spruce_sapling"}},tag=ud_dispenser_replant_spruce] if block ~ ~ ~ minecraft:air run setblock ~ ~ ~ minecraft:spruce_sapling
execute if entity @s[nbt={Item:{id:"minecraft:spruce_sapling"}},tag=ud_dispenser_replant_spruce] if block ~ ~ ~ minecraft:spruce_sapling run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:birch_sapling"}},tag=ud_dispenser_replant_birch] if block ~ ~ ~ minecraft:air run setblock ~ ~ ~ minecraft:birch_sapling
execute if entity @s[nbt={Item:{id:"minecraft:birch_sapling"}},tag=ud_dispenser_replant_birch] if block ~ ~ ~ minecraft:birch_sapling run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:jungle_sapling"}},tag=ud_dispenser_replant_jungle] if block ~ ~ ~ minecraft:air run setblock ~ ~ ~ minecraft:jungle_sapling
execute if entity @s[nbt={Item:{id:"minecraft:jungle_sapling"}},tag=ud_dispenser_replant_jungle] if block ~ ~ ~ minecraft:jungle_sapling run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:acacia_sapling"}},tag=ud_dispenser_replant_acacia] if block ~ ~ ~ minecraft:air run setblock ~ ~ ~ minecraft:acacia_sapling
execute if entity @s[nbt={Item:{id:"minecraft:acacia_sapling"}},tag=ud_dispenser_replant_acacia] if block ~ ~ ~ minecraft:acacia_sapling run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_sapling"}},tag=ud_dispenser_replant_dark_oak] if block ~ ~ ~ minecraft:air run setblock ~ ~ ~ minecraft:dark_oak_sapling
execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_sapling"}},tag=ud_dispenser_replant_dark_oak] if block ~ ~ ~ minecraft:dark_oak_sapling run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:chorus_flower"}},tag=ud_dispenser_replant_chorus] if block ~ ~ ~ minecraft:air run setblock ~ ~ ~ minecraft:chorus_flower
execute if entity @s[nbt={Item:{id:"minecraft:chorus_flower"}},tag=ud_dispenser_replant_chorus] if block ~ ~ ~ minecraft:chorus_flower run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:nether_wart"}},tag=ud_dispenser_replant_wart] if block ~ ~ ~ minecraft:air run setblock ~ ~ ~ minecraft:nether_wart
execute if entity @s[nbt={Item:{id:"minecraft:nether_wart"}},tag=ud_dispenser_replant_wart] if block ~ ~ ~ minecraft:nether_wart run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air if block ~1 ~ ~ minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=east]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air if block ~1 ~ ~ minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=east]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log if block ~-1 ~ ~ minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=west]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood if block ~-1 ~ ~ minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=west]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log if block ~-1 ~ ~ minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=west]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood if block ~-1 ~ ~ minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=west]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=south]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=south]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_wood if block ~ ~ ~1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=south]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_wood if block ~ ~ ~1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=south]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=south]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=south]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_wood if block ~ ~ ~1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=south]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_wood if block ~ ~ ~1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=south]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_log unless block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_log unless block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_wood unless block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_wood unless block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_log unless block ~ ~ ~1 minecraft:jungle_wood if block ~ ~ ~-1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_log unless block ~ ~ ~1 minecraft:jungle_wood if block ~ ~ ~-1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_wood unless block ~ ~ ~1 minecraft:jungle_wood if block ~ ~ ~-1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_wood unless block ~ ~ ~1 minecraft:jungle_wood if block ~ ~ ~-1 minecraft:jungle_log run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_log unless block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_log unless block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_wood unless block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_wood unless block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_log unless block ~ ~ ~1 minecraft:jungle_wood if block ~ ~ ~-1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_log unless block ~ ~ ~1 minecraft:jungle_wood if block ~ ~ ~-1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_log unless block ~-1 ~ ~ minecraft:jungle_wood unless block ~ ~ ~1 minecraft:jungle_wood if block ~ ~ ~-1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:air unless block ~1 ~ ~ minecraft:jungle_wood unless block ~-1 ~ ~ minecraft:jungle_wood unless block ~ ~ ~1 minecraft:jungle_wood if block ~ ~ ~-1 minecraft:jungle_wood run setblock ~ ~ ~ minecraft:cocoa[facing=north]
execute if entity @s[nbt={Item:{id:"minecraft:cocoa_beans"}},tag=ud_dispenser_replant_cocoa] if block ~ ~ ~ minecraft:cocoa run kill @s

execute positioned ~ ~-1 ~ run function unnamedde:misc/dispenser_plant/plant_not_full
