#######
# Compiled from unnamedde/functions/misc/dispenser_plant.mcscript
# to .//data/unnamedde/functions/misc/dispenser_plant/plant_not_full.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[nbt={Item:{id:"minecraft:wheat_seeds"}}] if block ~ ~1 ~ minecraft:air if block ~ ~ ~ minecraft:farmland run tag @s add ud_dispenser_replant_wheat

execute if entity @s[nbt={Item:{id:"minecraft:beetroot_seeds"}}] if block ~ ~1 ~ minecraft:air if block ~ ~ ~ minecraft:farmland run tag @s add ud_dispenser_replant_beetroot

execute if entity @s[nbt={Item:{id:"minecraft:pumpkin_seeds"}}] if block ~ ~1 ~ minecraft:air if block ~ ~ ~ minecraft:farmland run tag @s add ud_dispenser_replant_pumpkin

execute if entity @s[nbt={Item:{id:"minecraft:melon_seeds"}}] if block ~ ~1 ~ minecraft:air if block ~ ~ ~ minecraft:farmland run tag @s add ud_dispenser_replant_melon

execute if entity @s[nbt={Item:{id:"minecraft:potato"}}] if block ~ ~1 ~ minecraft:air if block ~ ~ ~ minecraft:farmland run tag @s add ud_dispenser_replant_potato

execute if entity @s[nbt={Item:{id:"minecraft:carrot"}}] if block ~ ~1 ~ minecraft:air if block ~ ~ ~ minecraft:farmland run tag @s add ud_dispenser_replant_carrots

execute if entity @s[nbt={Item:{id:"minecraft:wheat_seeds"}},tag=ud_dispenser_replant_wheat] if block ~ ~1 ~ minecraft:air run setblock ~ ~1 ~ minecraft:wheat
execute if entity @s[nbt={Item:{id:"minecraft:wheat_seeds"}},tag=ud_dispenser_replant_wheat] if block ~ ~1 ~ minecraft:wheat run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:beetroot_seeds"}},tag=ud_dispenser_replant_beetroot] if block ~ ~1 ~ minecraft:air run setblock ~ ~1 ~ minecraft:beetroots
execute if entity @s[nbt={Item:{id:"minecraft:beetroot_seeds"}},tag=ud_dispenser_replant_beetroot] if block ~ ~1 ~ minecraft:beetroots run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:pumpkin_seeds"}},tag=ud_dispenser_replant_pumpkin] if block ~ ~1 ~ minecraft:air run setblock ~ ~1 ~ minecraft:pumpkin_stem
execute if entity @s[nbt={Item:{id:"minecraft:pumpkin_seeds"}},tag=ud_dispenser_replant_pumpkin] if block ~ ~1 ~ minecraft:pumpkin_stem run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:melon_seeds"}},tag=ud_dispenser_replant_melon] if block ~ ~1 ~ minecraft:air run setblock ~ ~1 ~ minecraft:melon_stem
execute if entity @s[nbt={Item:{id:"minecraft:melon_seeds"}},tag=ud_dispenser_replant_melon] if block ~ ~1 ~ minecraft:melon_stem run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:potato"}},tag=ud_dispenser_replant_potato] if block ~ ~1 ~ minecraft:air run setblock ~ ~1 ~ minecraft:potatoes
execute if entity @s[nbt={Item:{id:"minecraft:potato"}},tag=ud_dispenser_replant_potato] if block ~ ~1 ~ minecraft:potatoes run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:carrot"}},tag=ud_dispenser_replant_carrot] if block ~ ~1 ~ minecraft:air run setblock ~ ~1 ~ minecraft:carrots
execute if entity @s[nbt={Item:{id:"minecraft:carrot"}},tag=ud_dispenser_replant_carrot] if block ~ ~1 ~ minecraft:carrots run kill @s
