#######
# Compiled from data/smash_lib/functions/invulnerable.mcscript
# to .//data/smash_lib/functions/invulnerable/vulnerable.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove smash_lib_invulnerable
data merge entity @s[type=item] {Invulnerable:0b}