#######
# Compiled from data/ac_lib/functions/remove.mcscript
# to .//data/ac_lib/functions/remove/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:remove/craftingtable/detect
