#######
# Compiled from data/smash_lib/functions/detect.mcscript
# to .//data/smash_lib/functions/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######


#For the anvil stuff
execute at @e[type=falling_block,nbt={BlockState:{Name:"minecraft:anvil"}}] as @e[distance=..1.75,type=!falling_block] at @s if entity @s[type=item,tag=!smash_lib_invulnerable] run function smash_lib:invulnerable/invulnerable
execute at @e[type=falling_block,nbt={BlockState:{Name:"minecraft:chipped_anvil"}}] as @e[distance=..1.75,type=!falling_block] at @s if entity @s[type=item,tag=!smash_lib_invulnerable] run function smash_lib:invulnerable/invulnerable
execute at @e[type=falling_block,nbt={BlockState:{Name:"minecraft:damaged_anvil"}}] as @e[distance=..1.75,type=!falling_block] at @s if entity @s[type=item,tag=!smash_lib_invulnerable] run function smash_lib:invulnerable/invulnerable
execute at @e[type=falling_block,nbt={BlockState:{Name:"minecraft:anvil"}}] as @e[distance=..1.75,type=!falling_block] at @s unless entity @s[scores={smash_anvil=1..}] unless entity @s[scores={smash_anvil_cool=1..}] run scoreboard players set @s smash_anvil 1
execute at @e[type=falling_block,nbt={BlockState:{Name:"minecraft:chipped_anvil"}}] as @e[distance=..1.75,type=!falling_block] at @s unless entity @s[scores={smash_anvil=1..}] unless entity @s[scores={smash_anvil_cool=1..}] run scoreboard players set @s smash_anvil 1
execute at @e[type=falling_block,nbt={BlockState:{Name:"minecraft:damaged_anvil"}}] as @e[distance=..1.75,type=!falling_block] at @s unless entity @s[scores={smash_anvil=1..}] unless entity @s[scores={smash_anvil_cool=1..}] run scoreboard players set @s smash_anvil 1


#For the piston stuff
execute as @e[type=minecraft:item] at @s unless entity @s[scores={smash_pston_cool=1..}] if block ~ ~1 ~ minecraft:piston[facing=down,extended=true] run scoreboard players set @s smash_piston 1