#######
# Compiled from data/smash_lib/functions/example.mcscript
# to .//data/smash_lib/functions/example.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=smash_anvil,type=item,nbt={Item:{id:"minecraft:iron_block",Count:1b}}] run data merge entity @s {Item:{id:"minecraft:heavy_weighted_pressure_plate",Count:5b}}
execute as @e[tag=smash_piston,type=item,nbt={Item:{id:"minecraft:iron_block",Count:1b}}] run data merge entity @s {Item:{id:"minecraft:iron_ingot",Count:9b}}