#######
# Compiled from data/smash_lib/functions/load.mcscript
# to .//data/smash_lib/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function smash_lib:mcscript/load

scoreboard objectives add smash_anvil dummy "Smashed by anvil"
scoreboard objectives add smash_anvil_cool dummy "Anvil smash cooldown"
scoreboard objectives add smash_piston dummy "Smashed by piston"
scoreboard objectives add smash_pston_cool dummy "Piston smash cooldown"