#######
# Compiled from data/smash_lib/functions/main.mcscript
# to .//data/smash_lib/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function smash_lib:detect
function smash_lib:action/main
function smash_lib:invulnerable/main
#examples
function smash_lib:example
