#######
# Compiled from unnamedde/functions/misc/money_additions.mcscript
# to .//data/unnamedde/functions/misc/money_additions/check/extract_money.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result score @s ud_temp run data get entity @s SelectedItem.tag.unnamedDE.storedMoney
scoreboard players operation @s money += @s ud_temp
replaceitem entity @s weapon.mainhand air
scoreboard players reset @s ud_temp
scoreboard players reset @s extract_out_item
