#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/recipes/salt/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:dead_bubble_coral{CustomModelData:7050004,display:{Name:"{\"translate\":\"Salt\",\"italic\":false}"},ac_lib:{id:"salt",NoPlacing:1}} 1
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_salt
