#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/recipes/salt.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[tag=!ac_lib_advanced_crafter_crafted] if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:1b,id:"minecraft:water_bucket"}]} if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:2b,id:"minecraft:water_bucket"}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:3b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:10b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:11b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:12b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:19b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:20b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:21b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot: 16b}]} run function ac_lib:advanced_crafter/recipes/salt/1

execute if entity @s[tag=ac_lib_advanced_crafter_crafted_salt] if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:1b,id:"minecraft:water_bucket"}]} if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:2b,id:"minecraft:water_bucket"}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:3b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:10b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:11b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:12b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:19b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:20b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:21b}]} unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot: 16b,Count:1b,id:"minecraft:dead_bubble_coral",tag:{CustomModelData:7050004,display:{Name:"{\"translate\":\"Salt\",\"italic\":false}"},ac_lib:{id:"salt",NoPlacing:1}}}]} run function ac_lib:advanced_crafter/recipes/salt/2

execute if entity @s[tag=ac_lib_advanced_crafter_crafted_salt] if block ~ ~ ~ minecraft:gray_shulker_box unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:1b,id:"minecraft:water_bucket"}]} run function ac_lib:advanced_crafter/recipes/salt/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_salt] if block ~ ~ ~ minecraft:gray_shulker_box unless block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:2b,id:"minecraft:water_bucket"}]} run function ac_lib:advanced_crafter/recipes/salt/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_salt] if block ~ ~ ~ minecraft:gray_shulker_box if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:3b}]} run function ac_lib:advanced_crafter/recipes/salt/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_salt] if block ~ ~ ~ minecraft:gray_shulker_box if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:10b}]} run function ac_lib:advanced_crafter/recipes/salt/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_salt] if block ~ ~ ~ minecraft:gray_shulker_box if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:11b}]} run function ac_lib:advanced_crafter/recipes/salt/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_salt] if block ~ ~ ~ minecraft:gray_shulker_box if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:12b}]} run function ac_lib:advanced_crafter/recipes/salt/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_salt] if block ~ ~ ~ minecraft:gray_shulker_box if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:19b}]} run function ac_lib:advanced_crafter/recipes/salt/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_salt] if block ~ ~ ~ minecraft:gray_shulker_box if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:20b}]} run function ac_lib:advanced_crafter/recipes/salt/3
execute if entity @s[tag=ac_lib_advanced_crafter_crafted_salt] if block ~ ~ ~ minecraft:gray_shulker_box if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:21b}]} run function ac_lib:advanced_crafter/recipes/salt/3

execute if entity @s[tag=ac_lib_advanced_crafter_crafted_salt] if block ~ ~ ~ minecraft:air run kill @e[type=minecraft:item,limit=1,sort=nearest,nbt={Item:{Count:1b,tag:{CustomModelData:7050004,display:{Name:"{\"translate\":\"Salt\",\"italic\":false}"},ac_lib:{id:"salt",NoPlacing:1}}, id:"minecraft:dead_bubble_coral"}}]

