#######
# Compiled from data/ac_lib/functions/create.mcscript
# to .//data/ac_lib/functions/create/craftingtable/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=armor_stand,tag=aclib_craftingtable,tag=aclib_craftingtable_init] at @s run function ac_lib:create/craftingtable/place
