#######
# Compiled from unnamedde/functions/misc/bonsai_pots.mcscript
# to .//data/unnamedde/functions/misc/bonsai_pots/action.mcfunction
#
# Generated by Minecraft Script for 1.13
######
playsound minecraft:item.axe.strip block @a


#Trees
execute if block ~ ~1 ~ minecraft:potted_oak_sapling run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/oak

execute if block ~ ~1 ~ minecraft:potted_spruce_sapling run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/spruce

execute if block ~ ~1 ~ minecraft:potted_birch_sapling run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/birch

execute if block ~ ~1 ~ minecraft:potted_jungle_sapling run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/jungle

execute if block ~ ~1 ~ minecraft:potted_acacia_sapling run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/acacia

execute if block ~ ~1 ~ minecraft:potted_dark_oak_sapling run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/dark_oak

execute if block ~ ~1 ~ minecraft:potted_bamboo run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/bamboo

execute if block ~ ~1 ~ minecraft:potted_cactus run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/cactus

execute if block ~ ~1 ~ minecraft:potted_brown_mushroom run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/brown_mushroom

execute if block ~ ~1 ~ minecraft:potted_red_mushroom run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/red_mushroom

execute if block ~ ~1 ~ minecraft:potted_dead_bush run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/dead_bush

execute if block ~ ~1 ~ minecraft:potted_fern run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/fern

#Flowers
execute if block ~ ~1 ~ minecraft:potted_dandelion run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/dandelion

execute if block ~ ~1 ~ minecraft:potted_poppy run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/poppy

execute if block ~ ~1 ~ minecraft:potted_blue_orchid run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/blue_orchid

execute if block ~ ~1 ~ minecraft:potted_allium run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/allium

execute if block ~ ~1 ~ minecraft:potted_azure_bluet run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/azure_bluet

execute if block ~ ~1 ~ minecraft:potted_red_tulip run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/red_tulip

execute if block ~ ~1 ~ minecraft:potted_orange_tulip run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/orange_tulip

execute if block ~ ~1 ~ minecraft:potted_white_tulip run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/white_tulip

execute if block ~ ~1 ~ minecraft:potted_pink_tulip run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/pink_tulip

execute if block ~ ~1 ~ minecraft:potted_oxeye_daisy run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/oxeye_daisy

execute if block ~ ~1 ~ minecraft:potted_cornflower run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/cornflower

execute if block ~ ~1 ~ minecraft:potted_lily_of_the_valley run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/lily_of_the_valley

execute if block ~ ~1 ~ minecraft:potted_wither_rose run loot insert ~ ~ ~ loot unnamedde:bonsai_pots/wither_rose

