#######
# Compiled from data/unnamedde/functions/creative_menu.mcscript
# to .//data/unnamedde/functions/creative_menu/give.mcfunction
#
# Generated by Minecraft Script for 1.13
######

#Ender Upgrade
execute if score @s ud_creative_menu matches 11 run give @s minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Ender Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Put in a item frame on a hopper to\",\"color\":\"green\",\"italic\":false}","{\"text\":\"enable ender pickup of all items around\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701005,unnamedDE:{id:"ender_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 1
execute if score @s ud_creative_menu matches 11 run scoreboard players reset @s ud_creative_menu

execute if score @s ud_creative_menu matches 21 run give @s minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Ender Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Put in a item frame on a hopper to\",\"color\":\"green\",\"italic\":false}","{\"text\":\"enable ender pickup of all items around\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701005,unnamedDE:{id:"ender_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 64
execute if score @s ud_creative_menu matches 21 run scoreboard players reset @s ud_creative_menu

#Wireless Upgrade
execute if score @s ud_creative_menu matches 12 run give @s minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Wireless Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Put in a item frame next to a\",\"color\":\"green\",\"italic\":false}","{\"text\":\"redstone block\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701003,unnamedDE:{id:"wireless_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 1
execute if score @s ud_creative_menu matches 12 run scoreboard players reset @s ud_creative_menu

execute if score @s ud_creative_menu matches 22 run give @s minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Wireless Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Put in a item frame next to a\",\"color\":\"green\",\"italic\":false}","{\"text\":\"redstone block\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701003,unnamedDE:{id:"wireless_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 64
execute if score @s ud_creative_menu matches 22 run scoreboard players reset @s ud_creative_menu

#XP Container
execute if score @s ud_creative_menu matches 13 run give @s minecraft:dead_bubble_coral{CustomModelData:701001,unnamedDE:{id:"xp_container",storedXP:0,NoPlacing:1},display:{Name:"{\"text\":\"XP Container\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Used to store XP\",\"color\":\"dark_green\",\"italic\":false}"]},HideFlags:1,Enchantments:[{id:"minecraft:protection",lvl:1}]} 1
execute if score @s ud_creative_menu matches 13 run scoreboard players reset @s ud_creative_menu

execute if score @s ud_creative_menu matches 23 run give @s minecraft:dead_bubble_coral{CustomModelData:701001,unnamedDE:{id:"xp_container",storedXP:0,NoPlacing:1},display:{Name:"{\"text\":\"XP Container\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Used to store XP\",\"color\":\"dark_green\",\"italic\":false}"]},HideFlags:1,Enchantments:[{id:"minecraft:protection",lvl:1}]} 64
execute if score @s ud_creative_menu matches 23 run scoreboard players reset @s ud_creative_menu

#Bonsai Upgrade
execute if score @s ud_creative_menu matches 14 run give @s minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Bonsai Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Put in a item frame next to a\",\"color\":\"green\",\"italic\":false}","{\"text\":\"block with an inventory and place a flower pot\",\"color\":\"green\",\"italic\":false}","{\"text\":\"with your desired sapling on top\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701002,unnamedDE:{id:"bonsai_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 1
execute if score @s ud_creative_menu matches 14 run scoreboard players reset @s ud_creative_menu

execute if score @s ud_creative_menu matches 24 run give @s minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Bonsai Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Put in a item frame next to a\",\"color\":\"green\",\"italic\":false}","{\"text\":\"block with an inventory and place a flower pot\",\"color\":\"green\",\"italic\":false}","{\"text\":\"with your desired sapling on top\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701002,unnamedDE:{id:"bonsai_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 64
execute if score @s ud_creative_menu matches 24 run scoreboard players reset @s ud_creative_menu

#Trash Can
execute if score @s ud_creative_menu matches 15 run give @s minecraft:armor_stand{CustomModelData:701002,unnamedDE:{id:"trash_can_place"},display:{Name:"{\"translate\":\"Trashcan\",\"italic\":\"false\"}",Lore:["{\"translate\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"]},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["ud_trash_can","ud_trash_can_init"]}} 1
execute if score @s ud_creative_menu matches 15 run scoreboard players reset @s ud_creative_menu

execute if score @s ud_creative_menu matches 25 run give @s minecraft:armor_stand{CustomModelData:701002,unnamedDE:{id:"trash_can_place"},display:{Name:"{\"translate\":\"Trashcan\",\"italic\":\"false\"}",Lore:["{\"translate\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"]},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["ud_trash_can","ud_trash_can_init"]}} 16
execute if score @s ud_creative_menu matches 25 run scoreboard players reset @s ud_creative_menu

#Storage Upgrade
execute if score @s ud_creative_menu matches 16 run give @s minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Storage Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Place in a item frame on a\",\"color\":\"green\",\"italic\":false}","{\"text\":\"stripped wood to have\",\"color\":\"green\",\"italic\":false}","{\"text\":\"infinite storage\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701006,unnamedDE:{id:"storage_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 1
execute if score @s ud_creative_menu matches 16 run scoreboard players reset @s ud_creative_menu

execute if score @s ud_creative_menu matches 26 run give @s minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Storage Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Place in a item frame on a\",\"color\":\"green\",\"italic\":false}","{\"text\":\"stripped wood to have\",\"color\":\"green\",\"italic\":false}","{\"text\":\"infinite storage\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701006,unnamedDE:{id:"storage_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 64
execute if score @s ud_creative_menu matches 26 run scoreboard players reset @s ud_creative_menu
