#######
# Compiled from data/unnamedde/functions/creative_menu.mcscript
# to .//data/unnamedde/functions/creative_menu/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a run function unnamedde:creative_menu/give
