#######
# Compiled from data/unnamedde/functions/creative_menu.mcscript
# to .//data/unnamedde/functions/creative_menu/menu.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s {"text":""}
tellraw @s {"text":""}
tellraw @s [{"text":"<===== ","color":"aqua"},{"text":"unnamed Core","color":"red"},{"text":" =====>","color":"aqua"}]
tellraw @s {"text":""}
#Content

#Wireless Upgrade
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 11"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 21"}},{"text":"] ","color":"reset"},{"text":"Ender Upgrade"}]
#Wireless Upgrade
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 12"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 22"}},{"text":"] ","color":"reset"},{"text":"Wireless Upgrade"}]
#XP Container
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 13"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 23"}},{"text":"] ","color":"reset"},{"text":"XP Container"}]
#Bonsai Upgrade
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 14"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 24"}},{"text":"] ","color":"reset"},{"text":"Bonsai Upgrade"}]
#Bonsai Upgrade
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 16"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 26"}},{"text":"] ","color":"reset"},{"text":"Storage Upgrade"}]
#Trash Can
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 15"}},{"text":"] [","color":"reset"},{"text":"16","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ud_creative_menu 25"}},{"text":"] ","color":"reset"},{"text":"Trash Can"}]
tellraw @s {"text":""}
tellraw @s [{"text":" ↑ ","color":"red"},{"text":"Return to main menu","hoverEvent":{"action":"show_text","value":"Click to return"},"clickEvent":{"action":"run_command","value":"/function unnamed_core:creative_menu"}}]
tellraw @s {"text":""}
tellraw @s {"text":""}
