#######
# Compiled from data/unnamedde/functions/creative_menu.mcscript
# to .//data/unnamedde/functions/creative_menu/select.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s [{"text":" ► ","color":"green"},{"text":"unnamed tweaks","hoverEvent":{"action":"show_text","value":"Click to select"},"clickEvent":{"action":"run_command","value":"/function unnamedde:creative_menu/menu"}}]
