#######
# Compiled from unnamedde/functions/misc/nightpvp.mcscript
# to .//data/unnamedde/functions/misc/nightpvp/disable.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[team=,] run team join nopvp