#######
# Compiled from unnamedde/functions/misc/nightpvp.mcscript
# to .//data/unnamedde/functions/misc/nightpvp/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score daytime ud_misc matches 0..12999 run function unnamedde:misc/nightpvp/disable
execute unless score daytime ud_misc matches 0..12999 run function unnamedde:misc/nightpvp/enable
