#######
# Compiled from unnamedde/functions/misc/nightpvp.mcscript
# to .//data/unnamedde/functions/misc/nightpvp/reset.mcfunction
#
# Generated by Minecraft Script for 1.13
######
team empty nopvp
scoreboard players set nightpvp ud_options -1