#######
# Compiled from unnamedde/functions/misc/crossbow_bolts.mcscript
# to .//data/unnamedde/functions/misc/crossbow_bolts/inground.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ud_inground
execute if entity @s[tag=ud_bolts_thunderbolt] run summon lightning_bolt
execute if entity @s[tag=ud_bolts_thunderbolt] run kill @s[type=arrow]

