#######
# Compiled from unnamedde/functions/misc/crossbow_bolts.mcscript
# to .//data/unnamedde/functions/misc/crossbow_bolts/shoot.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data modify entity @e[type=arrow,limit=1,sort=nearest,distance=..2] Color set value -1
execute if entity @s[tag=ud_bolts_bolt] run data modify entity @e[type=arrow,limit=1,sort=nearest,distance=..2] damage set value 4.0d

execute if entity @s[tag=ud_bolts_thunderbolt] run tag @e[type=arrow,limit=1,sort=nearest,distance=..2] add ud_bolts
execute if entity @s[tag=ud_bolts_thunderbolt] run tag @e[type=arrow,limit=1,sort=nearest,distance=..2] add ud_bolts_thunderbolt

