#######
# Compiled from unnamedde/functions/misc/encrypted_books.mcscript
# to .//data/unnamedde/functions/misc/encrypted_books/craft/decrypt/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data modify block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.key_test set from block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.key
execute store success score @s ud_temp run data modify block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.key_test set from block ~ ~ ~ Items[{Slot:2b}].tag.display.Name
execute if score @s ud_temp matches 0 run function unnamedde:misc/encrypted_books/craft/decrypt/decrypt

scoreboard players reset @s ud_temp
