#######
# Compiled from unnamedde/functions/misc/encrypted_books.mcscript
# to .//data/unnamedde/functions/misc/encrypted_books/craft/decrypt/2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:advanced_crafter/crafted
tag @s remove ac_lib_advanced_crafter_crafted
tag @s remove ac_lib_advanced_crafter_crafted_encrypt_book_decrypt
