#######
# Compiled from unnamedde/functions/misc/encrypted_books.mcscript
# to .//data/unnamedde/functions/misc/encrypted_books/craft/decrypt/decrypt.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_encrypt_book_decrypt
replaceitem block ~ ~ ~ container.16 minecraft:written_book 1
data modify block ~ ~ ~ Items[{Slot:16b}].tag.pages set from block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.pages
data modify block ~ ~ ~ Items[{Slot:16b}].tag.title set from block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.title
data modify block ~ ~ ~ Items[{Slot:16b}].tag.author set from block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted.author
data modify block ~ ~ ~ Items[{Slot:16b}].tag.encrypted set from block ~ ~ ~ Items[{Slot:1b}].tag.unnamedDE.encrypted
