#######
# Compiled from unnamedde/functions/misc/bonsai_pots.mcscript
# to .//data/unnamedde/functions/misc/bonsai_pots/craft/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Bonsai Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Put in a item frame next to a\",\"color\":\"green\",\"italic\":false}","{\"text\":\"block with an inventory and place a flower pot\",\"color\":\"green\",\"italic\":false}","{\"text\":\"with your desired plant on top\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701002,unnamedDE:{id:"bonsai_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 1
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_bonsai_upgrade
