#######
# Compiled from data/ac_lib/functions/give.mcscript
# to .//data/ac_lib/functions/give/crafting_table.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:armor_stand{CustomModelData:702001,display:{Name:"{\"text\":\"Advanced Crafing Table\",\"color\":\"yellow\",\"italic\":\"false\"}",Lore:["{\"text\":\"Right-click to place\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}],EntityTag:{Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["aclib_craftingtable","aclib_craftingtable_init"],DisabledSlots:4144959}}