#######
# Compiled from unnamedde/functions/misc/xp_containers.mcscript
# to .//data/unnamedde/functions/misc/xp_containers/craft/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:dead_bubble_coral{CustomModelData:701001,unnamedDE:{id:"xp_container",storedXP:0,NoPlacing:1},display:{Name:"{\"text\":\"XP Container\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Used to store XP\",\"color\":\"dark_green\",\"italic\":false}"]},HideFlags:1,Enchantments:[{id:"minecraft:protection",lvl:1}]} 1
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_xp_container
