#######
# Compiled from unnamedde/functions/misc/replant_saplings.mcscript
# to .//data/unnamedde/functions/misc/replant_saplings/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=item,nbt={Item:{id:"minecraft:oak_sapling",Count:1b}}] at @s if score @s ud_counter matches 600.. if block ~ ~-1 ~ #unnamed_core:tree_plantable if block ~ ~ ~ minecraft:air run function unnamedde:misc/replant_saplings/replant
execute as @e[type=item,nbt={Item:{id:"minecraft:oak_sapling",Count:1b}}] at @s unless score @s ud_counter matches 600.. run scoreboard players add @s ud_counter 1
execute as @e[type=item,nbt={Item:{id:"minecraft:spruce_sapling",Count:1b}}] at @s if score @s ud_counter matches 600.. if block ~ ~-1 ~ #unnamed_core:tree_plantable if block ~ ~ ~ minecraft:air run function unnamedde:misc/replant_saplings/replant
execute as @e[type=item,nbt={Item:{id:"minecraft:spruce_sapling",Count:1b}}] at @s unless score @s ud_counter matches 600.. run scoreboard players add @s ud_counter 1
execute as @e[type=item,nbt={Item:{id:"minecraft:birch_sapling",Count:1b}}] at @s if score @s ud_counter matches 600.. if block ~ ~-1 ~ #unnamed_core:tree_plantable if block ~ ~ ~ minecraft:air run function unnamedde:misc/replant_saplings/replant
execute as @e[type=item,nbt={Item:{id:"minecraft:birch_sapling",Count:1b}}] at @s unless score @s ud_counter matches 600.. run scoreboard players add @s ud_counter 1
execute as @e[type=item,nbt={Item:{id:"minecraft:jungle_sapling",Count:1b}}] at @s if score @s ud_counter matches 600.. if block ~ ~-1 ~ #unnamed_core:tree_plantable if block ~ ~ ~ minecraft:air run function unnamedde:misc/replant_saplings/replant
execute as @e[type=item,nbt={Item:{id:"minecraft:jungle_sapling",Count:1b}}] at @s unless score @s ud_counter matches 600.. run scoreboard players add @s ud_counter 1
execute as @e[type=item,nbt={Item:{id:"minecraft:acacia_sapling",Count:1b}}] at @s if score @s ud_counter matches 600.. if block ~ ~-1 ~ #unnamed_core:tree_plantable if block ~ ~ ~ minecraft:air run function unnamedde:misc/replant_saplings/replant
execute as @e[type=item,nbt={Item:{id:"minecraft:acacia_sapling",Count:1b}}] at @s unless score @s ud_counter matches 600.. run scoreboard players add @s ud_counter 1
execute as @e[type=item,nbt={Item:{id:"minecraft:dark_oak_sapling",Count:1b}}] at @s if score @s ud_counter matches 600.. if block ~ ~-1 ~ #unnamed_core:tree_plantable if block ~ ~ ~ minecraft:air run function unnamedde:misc/replant_saplings/replant
execute as @e[type=item,nbt={Item:{id:"minecraft:dark_oak_sapling",Count:1b}}] at @s unless score @s ud_counter matches 600.. run scoreboard players add @s ud_counter 1
