#######
# Compiled from unnamedde/functions/misc/replant_saplings.mcscript
# to .//data/unnamedde/functions/misc/replant_saplings/replant.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[nbt={Item:{id:"minecraft:oak_sapling"}}] run setblock ~ ~ ~ minecraft:oak_sapling
execute if entity @s[nbt={Item:{id:"minecraft:oak_sapling"}}] run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:spruce_sapling"}}] run setblock ~ ~ ~ minecraft:spruce_sapling
execute if entity @s[nbt={Item:{id:"minecraft:spruce_sapling"}}] run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:birch_sapling"}}] run setblock ~ ~ ~ minecraft:birch_sapling
execute if entity @s[nbt={Item:{id:"minecraft:birch_sapling"}}] run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:jungle_sapling"}}] run setblock ~ ~ ~ minecraft:jungle_sapling
execute if entity @s[nbt={Item:{id:"minecraft:jungle_sapling"}}] run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:acacia_sapling"}}] run setblock ~ ~ ~ minecraft:acacia_sapling
execute if entity @s[nbt={Item:{id:"minecraft:acacia_sapling"}}] run kill @s

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_sapling"}}] run setblock ~ ~ ~ minecraft:dark_oak_sapling
execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_sapling"}}] run kill @s
