#######
# Compiled from unnamedde/functions/misc/wireless_redstone.mcscript
# to .//data/unnamedde/functions/misc/wireless_redstone/activate.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter as @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] if entity @s[nbt={Facing:4b}] positioned ~1 ~ ~ run function unnamedde:misc/wireless_redstone/activated
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter as @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] if entity @s[nbt={Facing:5b}] positioned ~-1 ~ ~ run function unnamedde:misc/wireless_redstone/activated
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter as @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] if entity @s[nbt={Facing:3b}] positioned ~ ~ ~-1 run function unnamedde:misc/wireless_redstone/activated
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter as @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] if entity @s[nbt={Facing:2b}] positioned ~ ~ ~1 run function unnamedde:misc/wireless_redstone/activated
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter as @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] if entity @s[nbt={Facing:1b}] positioned ~ ~-1 ~ run function unnamedde:misc/wireless_redstone/activated
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter as @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] if entity @e[nbt={Facing:0b}] unless entity @s[nbt={Facing:1b}] unless entity @s[nbt={Facing:2b}] unless entity @s[nbt={Facing:3b}] unless entity @s[nbt={Facing:4b}] unless entity @s[nbt={Facing:5b}] positioned ~ ~1 ~ run function unnamedde:misc/wireless_redstone/activated

