#######
# Compiled from unnamedde/functions/misc/wireless_redstone.mcscript
# to .//data/unnamedde/functions/misc/wireless_redstone/activated.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ud_activated
particle minecraft:portal ~ ~ ~ .1 .1 .1 1 1
setblock ~ ~ ~ minecraft:redstone_block
