#######
# Compiled from unnamedde/functions/misc/wireless_redstone.mcscript
# to .//data/unnamedde/functions/misc/wireless_redstone/deactivate.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter run particle dust 1 0 0 1 ~ ~ ~ 0 0 0 0 10
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter run tag @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] remove ud_activated
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter if entity @s[nbt={Facing:4b}] positioned ~1 ~ ~ run setblock ~ ~ ~ redstone_lamp
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter if entity @s[nbt={Facing:5b}] positioned ~-1 ~ ~ run setblock ~ ~ ~ redstone_lamp
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter if entity @s[nbt={Facing:3b}] positioned ~ ~ ~-1 run setblock ~ ~ ~ redstone_lamp
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter if entity @s[nbt={Facing:2b}] positioned ~ ~ ~1 run setblock ~ ~ ~ redstone_lamp
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter if entity @s[nbt={Facing:1b}] positioned ~ ~-1 ~ run setblock ~ ~ ~ redstone_lamp
execute if score @e[limit=1,sort=nearest,type=item_frame,tag=ud_wireless] ud_counter = @s ud_counter if entity @s[nbt={Facing:0b}] positioned ~ ~1 ~ run setblock ~ ~ ~ redstone_lamp

