#######
# Compiled from unnamedde/functions/misc/wireless_redstone.mcscript
# to .//data/unnamedde/functions/misc/wireless_redstone/main_.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[tag=!ud_activated] if block ~ ~ ~ minecraft:redstone_block run setblock ~ ~ ~ minecraft:redstone_lamp

tag @s[tag=ud_activated] remove ud_activated
execute as @a[distance=..5] at @s run scoreboard players enable @s set_frequency
execute if entity @s[tag=!ud_wireless] run function unnamedde:misc/wireless_redstone/init

execute if block ~ ~ ~ redstone_lamp[lit=true] if score @s ud_counter matches 1.. run tag @s add ud_active
execute if block ~ ~ ~ redstone_lamp[lit=true] if score @s ud_counter matches 1.. at @e[type=item_frame,tag=ud_wireless,limit=1,sort=nearest] at @e[type=item_frame,tag=ud_wireless,distance=.1..,tag=!ud_activated] run function unnamedde:misc/wireless_redstone/activate
execute unless block ~ ~ ~ redstone_lamp[lit=true] unless score @s ud_counter matches 1.. if entity @s[tag=ud_active] run tag @s remove ud_active
