#######
# Compiled from unnamedde/functions/misc/wireless_redstone.mcscript
# to .//data/unnamedde/functions/misc/wireless_redstone/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=ud_wireless,type=item_frame] at @s unless entity @s[nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] run function unnamedde:misc/wireless_redstone/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:4b}] positioned ~1 ~ ~ if block ~ ~ ~ #unnamedde:wireless_redstone_base run function unnamedde:misc/wireless_redstone/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:4b}] positioned ~1 ~ ~ unless block ~ ~ ~ #unnamedde:wireless_redstone_base if entity @s[tag=ud_wireless] run function unnamedde:misc/wireless_redstone/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:5b}] positioned ~-1 ~ ~ if block ~ ~ ~ #unnamedde:wireless_redstone_base run function unnamedde:misc/wireless_redstone/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:5b}] positioned ~-1 ~ ~ unless block ~ ~ ~ #unnamedde:wireless_redstone_base if entity @s[tag=ud_wireless] run function unnamedde:misc/wireless_redstone/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:3b}] positioned ~ ~ ~-1 if block ~ ~ ~ #unnamedde:wireless_redstone_base run function unnamedde:misc/wireless_redstone/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:3b}] positioned ~ ~ ~-1 unless block ~ ~ ~ #unnamedde:wireless_redstone_base if entity @s[tag=ud_wireless] run function unnamedde:misc/wireless_redstone/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:2b}] positioned ~ ~ ~1 if block ~ ~ ~ #unnamedde:wireless_redstone_base run function unnamedde:misc/wireless_redstone/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:2b}] positioned ~ ~ ~1 unless block ~ ~ ~ #unnamedde:wireless_redstone_base if entity @s[tag=ud_wireless] run function unnamedde:misc/wireless_redstone/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:1b}] positioned ~ ~-1 ~ if block ~ ~ ~ #unnamedde:wireless_redstone_base run function unnamedde:misc/wireless_redstone/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:1b}] positioned ~ ~-1 ~ unless block ~ ~ ~ #unnamedde:wireless_redstone_base if entity @s[tag=ud_wireless] run function unnamedde:misc/wireless_redstone/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:0b}] positioned ~ ~1 ~ if block ~ ~ ~ #unnamedde:wireless_redstone_base run function unnamedde:misc/wireless_redstone/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"wireless_upgrade"}}}}] at @s if entity @s[nbt={Facing:0b}] positioned ~ ~1 ~ unless block ~ ~ ~ #unnamedde:wireless_redstone_base if entity @s[tag=ud_wireless] run function unnamedde:misc/wireless_redstone/remove
execute as @a[scores={set_frequency=1..}] at @s run scoreboard players operation @e[tag=ud_wireless,limit=1,sort=nearest,type=item_frame] ud_counter = @s set_frequency
execute as @a[scores={set_frequency=1..}] at @s run scoreboard players reset @s set_frequency
execute as @a[scores={set_frequency=..-1}] at @s run scoreboard players reset @a[scores={set_frequency=..-1}] set_frequency
execute as @a[scores={set_frequency=0}] at @s unless entity @e[tag=ud_wireless,type=item_frame,distance=..5] run scoreboard players reset @s set_frequency
#Facing NBT-Data
