#######
# Compiled from unnamedde/functions/misc/wireless_redstone.mcscript
# to .//data/unnamedde/functions/misc/wireless_redstone/remove.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove ud_wireless
scoreboard players reset @s ud_counter
