#######
# Compiled from unnamedde/functions/misc/graves.mcscript
# to .//data/unnamedde/functions/misc/graves/admin_open_grave.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=ud_grave,limit=1,sort=nearest,distance=..2.5] at @s run function unnamedde:misc/graves/open_grave
