#######
# Compiled from unnamedde/functions/misc/graves.mcscript
# to .//data/unnamedde/functions/misc/graves/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=item] at @s store result score @s ud_age run data get entity @s Age
execute as @a[tag=ud_sneak, tag=ud_jump] at @s positioned ~ ~-.5 ~ if entity @e[tag=ud_grave,distance=...5] run function unnamedde:misc/graves/player_open_grave
