#######
# Compiled from unnamedde/functions/misc/graves.mcscript
# to .//data/unnamedde/functions/misc/graves/player_open_grave.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @e[tag=ud_grave,limit=1,sort=nearest,distance=..1,nbt={ArmorItems:[{},{},{},{tag:{unnamedDE:{graveMode:1}}}]}] if score @e[tag=ud_grave,limit=1,sort=nearest,distance=..1] ud_owner_id = @s group_id as @e[tag=ud_grave,limit=1,sort=nearest,distance=..1] at @s run function unnamedde:misc/graves/open_grave

execute if entity @e[tag=ud_grave,limit=1,sort=nearest,distance=..1,nbt={ArmorItems:[{},{},{},{tag:{unnamedDE:{graveMode:2}}}]}] if score @e[tag=ud_grave,limit=1,sort=nearest,distance=..1] ud_owner_id = @s player_id as @e[tag=ud_grave,limit=1,sort=nearest,distance=..1] at @s run function unnamedde:misc/graves/open_grave

