#######
# Compiled from unnamedde/functions/misc/crossbow_bolts.mcscript
# to .//data/unnamedde/functions/misc/crossbow_bolts/craft/bolt/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:arrow{unnamedDE:{IsBolt:1,id:"bolt"},display:{Name:"{\"text\":\"Bolt\",\"italic\":false}",Lore:["{\"text\":\"When used with a bow it acts like a normal arrow\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701001} 8
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_crossbow_bolt
