#######
# Compiled from unnamedde/functions/misc/tooltips.mcscript
# to .//data/unnamedde/functions/misc/tooltips/display/bow.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ud_tooltip_bow
title @s actionbar [{"text":"You have ","color":"green"},{"score":{"name":"@s","objective":"ud_arrowcount"},"color":"blue"},{"text":" arrows in your inventory","color":"green"}]
