#######
# Compiled from unnamedde/functions/misc/tooltips.mcscript
# to .//data/unnamedde/functions/misc/tooltips/display/clock.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ud_tooltip_clock
execute if entity @s[nbt={Dimension:0}] run title @s actionbar [{"text":"Time: ","color":"green"},{"score":{"name":"real_daytime","objective":"ud_misc"},"color":"yellow"},{"text":" (","color":"yellow"},{"score":{"name":"real_daytime%","objective":"ud_misc"},"color":"yellow"},{"text":"%)","color":"yellow"},{"text":" Day: ","color":"green"},{"score":{"name":"real_day","objective":"ud_misc"},"color":"yellow"}]
execute unless entity @s[nbt={Dimension:0}] if entity @s[nbt={Dimension:-1}] run title @s actionbar [{"text":"Time: ","color":"green","obfuscated":false},{"text":"00000","color":"yellow","obfuscated":true},{"text":" (","color":"yellow","obfuscated":false},{"text":"20","color":"yellow","obfuscated":true},{"text":"%)","color":"yellow","obfuscated":false},{"text":" Day: ","color":"green","obfuscated":false},{"text":"00","color":"yellow","obfuscated":true}]
execute unless entity @s[nbt={Dimension:0}] unless entity @s[nbt={Dimension:-1}] run title @s actionbar [{"text":"Time: ","color":"green","obfuscated":false},{"text":"It is the END","color":"yellow"}]
