#######
# Compiled from unnamedde/functions/misc/tooltips.mcscript
# to .//data/unnamedde/functions/misc/tooltips/display/clock.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ud_tooltip_clock
title @s actionbar [{"text":"Time: ","color":"green"},{"score":{"name":"real_daytime","objective":"ud_misc"},"color":"yellow"},{"text":" (","color":"yellow"},{"score":{"name":"real_daytime%","objective":"ud_misc"},"color":"yellow"},{"text":"%)","color":"yellow"},{"text":" Day: ","color":"green"},{"score":{"name":"real_day","objective":"ud_misc"},"color":"yellow"}]
