#######
# Compiled from unnamedde/functions/misc/tooltips.mcscript
# to .//data/unnamedde/functions/misc/tooltips/display/compass.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ud_tooltip_compass
title @s actionbar [{"text":"Coordinates: X: ","color":"green"},{"score":{"name":"@s","objective":"x_pos"},"color":"yellow"},{"text":" Y: ","color":"green"},{"score":{"name":"@s","objective":"y_pos"},"color":"yellow"},{"text":" Z: ","color":"green"},{"score":{"name":"@s","objective":"z_pos"},"color":"yellow"},{"text":" | ","color":"red"},{"text":"Rotation: X: ","color":"green"},{"score":{"name":"@s","objective":"x_rot"},"color":"blue"},{"text":" Y: ","color":"green"},{"score":{"name":"@s","objective":"y_rot"},"color":"blue"}]
