#######
# Compiled from unnamedde/functions/misc/tooltips.mcscript
# to .//data/unnamedde/functions/misc/tooltips/display/death_book.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ud_tooltip_death_book
title @s actionbar [{"text":"You died ","color":"green"},{"score":{"name":"@s","objective":"deaths"},"color":"yellow"},{"text":" times. You stayed alive for ","color":"green"},{"score":{"name":"@s","objective":"ud_deathtime_h"},"color":"yellow"},{"text":"h ","color":"yellow"},{"score":{"name":"@s","objective":"ud_deathtime_m"},"color":"yellow"},{"text":"m","color":"yellow"},{"text":". Your total playtime is ","color":"green"},{"score":{"name":"@s","objective":"ud_timeplayed_h"},"color":"yellow"},{"text":"h ","color":"yellow"},{"score":{"name":"@s","objective":"ud_timeplayed_m"},"color":"yellow"},{"text":"m","color":"yellow"},{"text":".","color":"green"}]
