#######
# Compiled from unnamedde/functions/misc/tooltips.mcscript
# to .//data/unnamedde/functions/misc/tooltips/display/elytra.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ud_tooltip_elytra
execute unless entity @s[nbt={SelectedItem:{id:"minecraft:compass"}}] if score @s y_rot matches ..-1 run title @p actionbar [{"text":"Pitch: ","color":"green"},{"score":{"name":"@s","objective":"y_rot"},"color":"blue"},{"text":" ↑","color":"yellow"}]
execute unless entity @s[nbt={SelectedItem:{id:"minecraft:compass"}}] unless score @s y_rot matches ..-1 run title @p actionbar [{"text":"Pitch: ","color":"green"},{"score":{"name":"@s","objective":"y_rot"},"color":"blue"},{"text":" ↓","color":"yellow"}]

