#######
# Compiled from unnamedde/functions/misc/tooltips.mcscript
# to .//data/unnamedde/functions/misc/tooltips/display/torch.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ud_tooltip_torch
title @s actionbar [{"text":"You have ","color":"green"},{"score":{"name":"@s","objective":"ud_torchcount"},"color":"blue"},{"text":" torches in your inventory","color":"green"}]
