#######
# Compiled from unnamedde/functions/misc/dispenser_planting.mcscript
# to .//data/unnamedde/functions/misc/dispenser_planting/plant/cocoa_east.mcfunction
#
# Generated by Minecraft Script for 1.13
######
kill @s[type=item]
setblock ~ ~ ~ minecraft:cocoa[facing=east]