#######
# Compiled from unnamedde/functions/misc/death_books.mcscript
# to .//data/unnamedde/functions/misc/death_books/death_sound.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score death_books ud_options matches 1.. run playsound minecraft:entity.wolf.howl ambient @s

