#######
# Compiled from unnamedde/functions/misc/death_books.mcscript
# to .//data/unnamedde/functions/misc/death_books/give_book.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score death_books ud_options matches 1.. run give @s minecraft:written_book{unnamedDE:{id:"book_of_death"},title:"Book of Death",author:"the death",generation:3,pages:["[{\"selector\":\"@s\",\"color\":\"dark_red\"},{\"text\":\" died on day \",\"color\":\"reset\"},{\"score\":{\"name\":\"real_day\",\"objective\":\"ud_misc\"},\"color\":\"reset\"},{\"text\":\" at X: \",\"color\":\"reset\"},{\"score\":{\"name\":\"@s\",\"objective\":\"death_x\"},\"color\":\"dark_red\"},{\"text\":\" Y: \",\"color\":\"reset\"},{\"score\":{\"name\":\"@s\",\"objective\":\"death_y\"},\"color\":\"dark_red\"},{\"text\":\" Z: \",\"color\":\"reset\"},{\"score\":{\"name\":\"@s\",\"objective\":\"death_z\"},\"color\":\"dark_red\"},{\"text\":\".\",\"color\":\"reset\"}]"]} 1
