#######
# Compiled from unnamedde/functions/misc/death_books.mcscript
# to .//data/unnamedde/functions/misc/death_books/give_book.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score death_books ud_options matches 1.. run give @s minecraft:written_book{unnamedDE:{id:"death_book"},title:"Book of Death",author:"the death",generation:3,resolved:1b,pages:["{\"text\":\"qwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnmqwertzuiopüasdfghjklöäyxcvbnm\",\"obfuscated\":true}"]} 1
execute if score death_books ud_options matches 1.. run tellraw @s [{"text":"You died at ","color":"red"},{"score":{"name":"@s","objective":"death_x"},"color":"blue"},{"text":" "},{"score":{"name":"@s","objective":"death_y"},"color":"blue"},{"text":" "},{"score":{"name":"@s","objective":"death_z"},"color":"blue"},{"text":" on day ","color":"red"},{"score":{"name":"real_day","objective":"ud_misc"},"color":"blue"}]

