#######
# Compiled from unnamedde/functions/misc/death_books.mcscript
# to .//data/unnamedde/functions/misc/death_books/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[scores={ud_deaths=1..},nbt={DeathTime:0s}] at @s if entity @s[tag=is_dead] run function unnamedde:misc/death_books/after_death
execute as @a[scores={ud_deaths=1..},nbt={DeathTime:0s}] at @s unless entity @s[tag=is_dead] run function unnamedde:misc/death_books/on_death
