#######
# Compiled from unnamedde/functions/misc/death_books.mcscript
# to .//data/unnamedde/functions/misc/death_books/on_death.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add is_dead
function #unnamedde:on_death
