#######
# Compiled from unnamedde/functions/misc/death_books.mcscript
# to .//data/unnamedde/functions/misc/death_books/reviving_sound.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score death_books ud_options matches 1.. run playsound minecraft:block.beacon.power_select master @s

