#######
# Compiled from unnamedde/functions/misc/functional_stonecutter.mcscript
# to .//data/unnamedde/functions/misc/functional_stonecutter/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=item_frame] at @s if data entity @s Item if entity @s[nbt={Rotation:[0.0f, 0.0f]}] if block ~ ~ ~-1 minecraft:stonecutter[facing=south] positioned ~ ~ ~-1 run function unnamedde:misc/functional_stonecutter/position
execute as @e[type=item_frame] at @s if data entity @s Item if entity @s[nbt={Rotation:[270.0f, 0.0f]}] if block ~-1 ~ ~ minecraft:stonecutter[facing=east] positioned ~-1 ~ ~ run function unnamedde:misc/functional_stonecutter/position
execute as @e[type=item_frame] at @s if data entity @s Item if entity @s[nbt={Rotation:[180.0f, 0.0f]}] if block ~ ~ ~1 minecraft:stonecutter[facing=north] positioned ~ ~ ~1 run function unnamedde:misc/functional_stonecutter/position
execute as @e[type=item_frame] at @s if data entity @s Item if entity @s[nbt={Rotation:[90.0f, 0.0f]}] if block ~1 ~ ~ minecraft:stonecutter[facing=west] positioned ~1 ~ ~ run function unnamedde:misc/functional_stonecutter/position
