#######
# Compiled from unnamedde/functions/misc/functional_stonecutter.mcscript
# to .//data/unnamedde/functions/misc/functional_stonecutter/position.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# Vanilla
execute if entity @s[nbt={Item:{id:"minecraft:chiseled_stone_bricks"}}] if block ~ ~1 ~ minecraft:stone run setblock ~ ~1 ~ minecraft:chiseled_stone_bricks replace

execute if entity @s[nbt={Item:{id:"minecraft:stone_brick_slab"}}] if block ~ ~1 ~ minecraft:stone run setblock ~ ~1 ~ minecraft:stone_brick_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:stone_brick_stairs"}}] if block ~ ~1 ~ minecraft:stone run setblock ~ ~1 ~ minecraft:stone_brick_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:stone_brick_wall"}}] if block ~ ~1 ~ minecraft:stone run setblock ~ ~1 ~ minecraft:stone_brick_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:stone_slab"}}] if block ~ ~1 ~ minecraft:stone run setblock ~ ~1 ~ minecraft:stone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:stone_stairs"}}] if block ~ ~1 ~ minecraft:stone run setblock ~ ~1 ~ minecraft:stone_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:stone_bricks"}}] if block ~ ~1 ~ minecraft:stone run setblock ~ ~1 ~ minecraft:stone_bricks replace

execute if entity @s[nbt={Item:{id:"minecraft:smooth_stone_slab"}}] if block ~ ~1 ~ minecraft:smooth_stone run setblock ~ ~1 ~ minecraft:smooth_stone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:stone_brick_slab"}}] if block ~ ~1 ~ minecraft:stone_bricks run setblock ~ ~1 ~ minecraft:stone_brick_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:stone_brick_stairs"}}] if block ~ ~1 ~ minecraft:stone_bricks run setblock ~ ~1 ~ minecraft:stone_brick_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:stone_brick_wall"}}] if block ~ ~1 ~ minecraft:stone_bricks run setblock ~ ~1 ~ minecraft:stone_brick_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:chiseled_stone_bricks"}}] if block ~ ~1 ~ minecraft:stone_bricks run setblock ~ ~1 ~ minecraft:chiseled_stone_bricks replace

execute if entity @s[nbt={Item:{id:"minecraft:mossy_stone_brick_slab"}}] if block ~ ~1 ~ minecraft:mossy_stone_bricks run setblock ~ ~1 ~ minecraft:mossy_stone_brick_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:mossy_stone_brick_stairs"}}] if block ~ ~1 ~ minecraft:mossy_stone_bricks run setblock ~ ~1 ~ minecraft:mossy_stone_brick_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:mossy_stone_brick_wall"}}] if block ~ ~1 ~ minecraft:mossy_stone_bricks run setblock ~ ~1 ~ minecraft:mossy_stone_brick_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:granite_slab"}}] if block ~ ~1 ~ minecraft:granite run setblock ~ ~1 ~ minecraft:granite_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:granite_stairs"}}] if block ~ ~1 ~ minecraft:granite run setblock ~ ~1 ~ minecraft:granite_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:granite_wall"}}] if block ~ ~1 ~ minecraft:granite run setblock ~ ~1 ~ minecraft:granite_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_granite"}}] if block ~ ~1 ~ minecraft:granite run setblock ~ ~1 ~ minecraft:polished_granite replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_granite_slab"}}] if block ~ ~1 ~ minecraft:granite run setblock ~ ~1 ~ minecraft:polished_granite_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_granite_stairs"}}] if block ~ ~1 ~ minecraft:granite run setblock ~ ~1 ~ minecraft:polished_granite_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_granite_slab"}}] if block ~ ~1 ~ minecraft:polished_granite run setblock ~ ~1 ~ minecraft:polished_granite_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_granite_stairs"}}] if block ~ ~1 ~ minecraft:polished_granite run setblock ~ ~1 ~ minecraft:polished_granite_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:diorite_slab"}}] if block ~ ~1 ~ minecraft:diorite run setblock ~ ~1 ~ minecraft:diorite_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:diorite_stairs"}}] if block ~ ~1 ~ minecraft:diorite run setblock ~ ~1 ~ minecraft:diorite_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:diorite_wall"}}] if block ~ ~1 ~ minecraft:diorite run setblock ~ ~1 ~ minecraft:diorite_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_diorite"}}] if block ~ ~1 ~ minecraft:diorite run setblock ~ ~1 ~ minecraft:polished_diorite replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_diorite_slab"}}] if block ~ ~1 ~ minecraft:diorite run setblock ~ ~1 ~ minecraft:polished_diorite_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_diorite_stairs"}}] if block ~ ~1 ~ minecraft:diorite run setblock ~ ~1 ~ minecraft:polished_diorite_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_diorite_slab"}}] if block ~ ~1 ~ minecraft:polished_diorite run setblock ~ ~1 ~ minecraft:polished_diorite_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_diorite_stairs"}}] if block ~ ~1 ~ minecraft:polished_diorite run setblock ~ ~1 ~ minecraft:polished_diorite_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:andesite_slab"}}] if block ~ ~1 ~ minecraft:andesite run setblock ~ ~1 ~ minecraft:andesite_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:andesite_stairs"}}] if block ~ ~1 ~ minecraft:andesite run setblock ~ ~1 ~ minecraft:andesite_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:andesite_wall"}}] if block ~ ~1 ~ minecraft:andesite run setblock ~ ~1 ~ minecraft:andesite_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_andesite"}}] if block ~ ~1 ~ minecraft:andesite run setblock ~ ~1 ~ minecraft:polished_andesite replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_andesite_slab"}}] if block ~ ~1 ~ minecraft:andesite run setblock ~ ~1 ~ minecraft:polished_andesite_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_andesite_stairs"}}] if block ~ ~1 ~ minecraft:andesite run setblock ~ ~1 ~ minecraft:polished_andesite_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_andesite_slab"}}] if block ~ ~1 ~ minecraft:polished_andesite run setblock ~ ~1 ~ minecraft:polished_andesite_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:polished_andesite_stairs"}}] if block ~ ~1 ~ minecraft:polished_andesite run setblock ~ ~1 ~ minecraft:polished_andesite_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:cobblestone_slab"}}] if block ~ ~1 ~ minecraft:cobblestone run setblock ~ ~1 ~ minecraft:cobblestone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:cobblestone_stairs"}}] if block ~ ~1 ~ minecraft:cobblestone run setblock ~ ~1 ~ minecraft:cobblestone_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:cobblestone_wall"}}] if block ~ ~1 ~ minecraft:cobblestone run setblock ~ ~1 ~ minecraft:cobblestone_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:mossy_cobblestone_slab"}}] if block ~ ~1 ~ minecraft:mossy_cobblestone run setblock ~ ~1 ~ minecraft:mossy_cobblestone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:mossy_cobblestone_stairs"}}] if block ~ ~1 ~ minecraft:mossy_cobblestone run setblock ~ ~1 ~ minecraft:mossy_cobblestone_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:mossy_cobblestone_wall"}}] if block ~ ~1 ~ minecraft:mossy_cobblestone run setblock ~ ~1 ~ minecraft:mossy_cobblestone_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:sandstone_slab"}}] if block ~ ~1 ~ minecraft:sandstone run setblock ~ ~1 ~ minecraft:sandstone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:sandstone_stairs"}}] if block ~ ~1 ~ minecraft:sandstone run setblock ~ ~1 ~ minecraft:sandstone_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:sandstone_wall"}}] if block ~ ~1 ~ minecraft:sandstone run setblock ~ ~1 ~ minecraft:sandstone_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:cut_sandstone"}}] if block ~ ~1 ~ minecraft:sandstone run setblock ~ ~1 ~ minecraft:cut_sandstone replace

execute if entity @s[nbt={Item:{id:"minecraft:cut_sandstone_slab"}}] if block ~ ~1 ~ minecraft:sandstone run setblock ~ ~1 ~ minecraft:cut_sandstone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:chiseled_sandstone"}}] if block ~ ~1 ~ minecraft:sandstone run setblock ~ ~1 ~ minecraft:chiseled_sandstone replace

execute if entity @s[nbt={Item:{id:"minecraft:cut_sandstone_slab"}}] if block ~ ~1 ~ minecraft:cut_sandstone run setblock ~ ~1 ~ minecraft:cut_sandstone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:smooth_sandstone_slab"}}] if block ~ ~1 ~ minecraft:smooth_sandstone run setblock ~ ~1 ~ minecraft:smooth_sandstone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:smooth_sandstone_stairs"}}] if block ~ ~1 ~ minecraft:smooth_sandstone run setblock ~ ~1 ~ minecraft:smooth_sandstone_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:red_sandstone_slab"}}] if block ~ ~1 ~ minecraft:red_sandstone run setblock ~ ~1 ~ minecraft:red_sandstone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:red_sandstone_stairs"}}] if block ~ ~1 ~ minecraft:red_sandstone run setblock ~ ~1 ~ minecraft:red_sandstone_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:red_sandstone_wall"}}] if block ~ ~1 ~ minecraft:red_sandstone run setblock ~ ~1 ~ minecraft:red_sandstone_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:cut_red_sandstone"}}] if block ~ ~1 ~ minecraft:red_sandstone run setblock ~ ~1 ~ minecraft:cut_red_sandstone replace

execute if entity @s[nbt={Item:{id:"minecraft:cut_red_sandstone_slab"}}] if block ~ ~1 ~ minecraft:red_sandstone run setblock ~ ~1 ~ minecraft:cut_red_sandstone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:chiseled_red_sandstone"}}] if block ~ ~1 ~ minecraft:red_sandstone run setblock ~ ~1 ~ minecraft:chiseled_red_sandstone replace

execute if entity @s[nbt={Item:{id:"minecraft:cut_red_sandstone_slab"}}] if block ~ ~1 ~ minecraft:cut_red_sandstone run setblock ~ ~1 ~ minecraft:cut_red_sandstone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:smooth_red_sandstone_slab"}}] if block ~ ~1 ~ minecraft:smooth_red_sandstone run setblock ~ ~1 ~ minecraft:smooth_red_sandstone_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:smooth_red_sandstone_stairs"}}] if block ~ ~1 ~ minecraft:smooth_red_sandstone run setblock ~ ~1 ~ minecraft:smooth_red_sandstone_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:prismarine_slab"}}] if block ~ ~1 ~ minecraft:prismarine run setblock ~ ~1 ~ minecraft:prismarine_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:prismarine_stairs"}}] if block ~ ~1 ~ minecraft:prismarine run setblock ~ ~1 ~ minecraft:prismarine_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:prismarine_wall"}}] if block ~ ~1 ~ minecraft:prismarine run setblock ~ ~1 ~ minecraft:prismarine_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:prismarine_brick_slab"}}] if block ~ ~1 ~ minecraft:prismarine_bricks run setblock ~ ~1 ~ minecraft:prismarine_brick_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:prismarine_brick_stairs"}}] if block ~ ~1 ~ minecraft:prismarine_bricks run setblock ~ ~1 ~ minecraft:prismarine_brick_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:dark_prismarine_slab"}}] if block ~ ~1 ~ minecraft:dark_prismarine run setblock ~ ~1 ~ minecraft:dark_prismarine_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:dark_prismarine_stairs"}}] if block ~ ~1 ~ minecraft:dark_prismarine run setblock ~ ~1 ~ minecraft:dark_prismarine_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:quartz_slab"}}] if block ~ ~1 ~ minecraft:quartz_block run setblock ~ ~1 ~ minecraft:quartz_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:quartz_stairs"}}] if block ~ ~1 ~ minecraft:quartz_block run setblock ~ ~1 ~ minecraft:quartz_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:chiseled_quartz_block"}}] if block ~ ~1 ~ minecraft:quartz_block run setblock ~ ~1 ~ minecraft:chiseled_quartz_block replace

execute if entity @s[nbt={Item:{id:"minecraft:quartz_pillar"}}] if block ~ ~1 ~ minecraft:quartz_block run setblock ~ ~1 ~ minecraft:quartz_pillar replace

execute if entity @s[nbt={Item:{id:"minecraft:smooth_quartz_slab"}}] if block ~ ~1 ~ minecraft:smooth_quartz run setblock ~ ~1 ~ minecraft:smooth_quartz_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:smooth_quartz_stairs"}}] if block ~ ~1 ~ minecraft:smooth_quartz run setblock ~ ~1 ~ minecraft:smooth_quartz_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:purpur_slab"}}] if block ~ ~1 ~ minecraft:purpur_block run setblock ~ ~1 ~ minecraft:purpur_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:purpur_stairs"}}] if block ~ ~1 ~ minecraft:purpur_block run setblock ~ ~1 ~ minecraft:purpur_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:purpur_pillar"}}] if block ~ ~1 ~ minecraft:purpur_block run setblock ~ ~1 ~ minecraft:purpur_pillar replace

execute if entity @s[nbt={Item:{id:"minecraft:brick_slab"}}] if block ~ ~1 ~ minecraft:bricks run setblock ~ ~1 ~ minecraft:brick_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:brick_stairs"}}] if block ~ ~1 ~ minecraft:bricks run setblock ~ ~1 ~ minecraft:brick_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:brick_wall"}}] if block ~ ~1 ~ minecraft:bricks run setblock ~ ~1 ~ minecraft:brick_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:nether_brick_slab"}}] if block ~ ~1 ~ minecraft:nether_bricks run setblock ~ ~1 ~ minecraft:nether_brick_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:nether_brick_stairs"}}] if block ~ ~1 ~ minecraft:nether_bricks run setblock ~ ~1 ~ minecraft:nether_brick_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:nether_brick_wall"}}] if block ~ ~1 ~ minecraft:nether_bricks run setblock ~ ~1 ~ minecraft:nether_brick_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:red_nether_brick_slab"}}] if block ~ ~1 ~ minecraft:red_nether_bricks run setblock ~ ~1 ~ minecraft:red_nether_brick_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:red_nether_brick_stairs"}}] if block ~ ~1 ~ minecraft:red_nether_bricks run setblock ~ ~1 ~ minecraft:red_nether_brick_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:red_nether_brick_wall"}}] if block ~ ~1 ~ minecraft:red_nether_bricks run setblock ~ ~1 ~ minecraft:red_nether_brick_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:end_stone_bricks"}}] if block ~ ~1 ~ minecraft:end_stone run setblock ~ ~1 ~ minecraft:end_stone_bricks replace

execute if entity @s[nbt={Item:{id:"minecraft:end_stone_brick_slab"}}] if block ~ ~1 ~ minecraft:end_stone run setblock ~ ~1 ~ minecraft:end_stone_brick_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:end_stone_brick_stairs"}}] if block ~ ~1 ~ minecraft:end_stone run setblock ~ ~1 ~ minecraft:end_stone_brick_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:end_stone_brick_wall"}}] if block ~ ~1 ~ minecraft:end_stone run setblock ~ ~1 ~ minecraft:end_stone_brick_wall replace

execute if entity @s[nbt={Item:{id:"minecraft:end_stone_brick_slab"}}] if block ~ ~1 ~ minecraft:end_stone_bricks run setblock ~ ~1 ~ minecraft:end_stone_brick_slab replace

execute if entity @s[nbt={Item:{id:"minecraft:end_stone_brick_stairs"}}] if block ~ ~1 ~ minecraft:end_stone_bricks run setblock ~ ~1 ~ minecraft:end_stone_brick_stairs replace

execute if entity @s[nbt={Item:{id:"minecraft:end_stone_brick_wall"}}] if block ~ ~1 ~ minecraft:end_stone_bricks run setblock ~ ~1 ~ minecraft:end_stone_brick_wall replace

# Unnamed Tweaks
execute if entity @s[nbt={Item:{id:"minecraft:black_carpet"}}] if block ~ ~1 ~ minecraft:black_wool run setblock ~ ~1 ~ minecraft:black_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:blue_carpet"}}] if block ~ ~1 ~ minecraft:blue_wool run setblock ~ ~1 ~ minecraft:blue_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:brown_carpet"}}] if block ~ ~1 ~ minecraft:brown_wool run setblock ~ ~1 ~ minecraft:brown_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:cyan_carpet"}}] if block ~ ~1 ~ minecraft:cyan_wool run setblock ~ ~1 ~ minecraft:cyan_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:gray_carpet"}}] if block ~ ~1 ~ minecraft:gray_wool run setblock ~ ~1 ~ minecraft:gray_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:green_carpet"}}] if block ~ ~1 ~ minecraft:green_wool run setblock ~ ~1 ~ minecraft:green_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:light_blue_carpet"}}] if block ~ ~1 ~ minecraft:light_blue_wool run setblock ~ ~1 ~ minecraft:light_blue_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:light_gray_carpet"}}] if block ~ ~1 ~ minecraft:light_gray_wool run setblock ~ ~1 ~ minecraft:light_gray_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:lime_carpet"}}] if block ~ ~1 ~ minecraft:lime_wool run setblock ~ ~1 ~ minecraft:lime_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:magenta_carpet"}}] if block ~ ~1 ~ minecraft:magenta_wool run setblock ~ ~1 ~ minecraft:magenta_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:orange_carpet"}}] if block ~ ~1 ~ minecraft:orange_wool run setblock ~ ~1 ~ minecraft:orange_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:pink_carpet"}}] if block ~ ~1 ~ minecraft:pink_wool run setblock ~ ~1 ~ minecraft:pink_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:purple_carpet"}}] if block ~ ~1 ~ minecraft:purple_wool run setblock ~ ~1 ~ minecraft:purple_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:red_carpet"}}] if block ~ ~1 ~ minecraft:red_wool run setblock ~ ~1 ~ minecraft:red_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:white_carpet"}}] if block ~ ~1 ~ minecraft:white_wool run setblock ~ ~1 ~ minecraft:white_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:yellow_carpet"}}] if block ~ ~1 ~ minecraft:yellow_wool run setblock ~ ~1 ~ minecraft:yellow_carpet replace

execute if entity @s[nbt={Item:{id:"minecraft:bell"}}] if block ~ ~1 ~ minecraft:gold_block run setblock ~ ~1 ~ minecraft:bell replace

execute if entity @s[nbt={Item:{id:"minecraft:carved_pumpkin"}}] if block ~ ~1 ~ minecraft:pumpkin run setblock ~ ~1 ~ minecraft:carved_pumpkin replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_fence"}}] if block ~ ~1 ~ minecraft:acacia_log run setblock ~ ~1 ~ minecraft:acacia_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_planks"}}] if block ~ ~1 ~ minecraft:acacia_log run setblock ~ ~1 ~ minecraft:acacia_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_acacia_log"}}] if block ~ ~1 ~ minecraft:acacia_log run setblock ~ ~1 ~ minecraft:stripped_acacia_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_acacia_wood"}}] if block ~ ~1 ~ minecraft:acacia_log run setblock ~ ~1 ~ minecraft:stripped_acacia_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_wood"}}] if block ~ ~1 ~ minecraft:acacia_log run setblock ~ ~1 ~ minecraft:acacia_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_fence"}}] if block ~ ~1 ~ minecraft:birch_log run setblock ~ ~1 ~ minecraft:birch_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_planks"}}] if block ~ ~1 ~ minecraft:birch_log run setblock ~ ~1 ~ minecraft:birch_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_birch_log"}}] if block ~ ~1 ~ minecraft:birch_log run setblock ~ ~1 ~ minecraft:stripped_birch_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_birch_wood"}}] if block ~ ~1 ~ minecraft:birch_log run setblock ~ ~1 ~ minecraft:stripped_birch_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_wood"}}] if block ~ ~1 ~ minecraft:birch_log run setblock ~ ~1 ~ minecraft:birch_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_fence"}}] if block ~ ~1 ~ minecraft:dark_oak_log run setblock ~ ~1 ~ minecraft:dark_oak_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_planks"}}] if block ~ ~1 ~ minecraft:dark_oak_log run setblock ~ ~1 ~ minecraft:dark_oak_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_dark_oak_log"}}] if block ~ ~1 ~ minecraft:dark_oak_log run setblock ~ ~1 ~ minecraft:stripped_dark_oak_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_dark_oak_wood"}}] if block ~ ~1 ~ minecraft:dark_oak_log run setblock ~ ~1 ~ minecraft:stripped_dark_oak_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_wood"}}] if block ~ ~1 ~ minecraft:dark_oak_log run setblock ~ ~1 ~ minecraft:dark_oak_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_fence"}}] if block ~ ~1 ~ minecraft:jungle_log run setblock ~ ~1 ~ minecraft:jungle_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_planks"}}] if block ~ ~1 ~ minecraft:jungle_log run setblock ~ ~1 ~ minecraft:jungle_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_jungle_log"}}] if block ~ ~1 ~ minecraft:jungle_log run setblock ~ ~1 ~ minecraft:stripped_jungle_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_jungle_wood"}}] if block ~ ~1 ~ minecraft:jungle_log run setblock ~ ~1 ~ minecraft:stripped_jungle_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_wood"}}] if block ~ ~1 ~ minecraft:jungle_log run setblock ~ ~1 ~ minecraft:jungle_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_fence"}}] if block ~ ~1 ~ minecraft:oak_log run setblock ~ ~1 ~ minecraft:oak_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_planks"}}] if block ~ ~1 ~ minecraft:oak_log run setblock ~ ~1 ~ minecraft:oak_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_oak_log"}}] if block ~ ~1 ~ minecraft:oak_log run setblock ~ ~1 ~ minecraft:stripped_oak_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_oak_wood"}}] if block ~ ~1 ~ minecraft:oak_log run setblock ~ ~1 ~ minecraft:stripped_oak_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_wood"}}] if block ~ ~1 ~ minecraft:oak_log run setblock ~ ~1 ~ minecraft:oak_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_fence"}}] if block ~ ~1 ~ minecraft:spruce_log run setblock ~ ~1 ~ minecraft:spruce_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_planks"}}] if block ~ ~1 ~ minecraft:spruce_log run setblock ~ ~1 ~ minecraft:spruce_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_spruce_log"}}] if block ~ ~1 ~ minecraft:spruce_log run setblock ~ ~1 ~ minecraft:stripped_spruce_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_spruce_wood"}}] if block ~ ~1 ~ minecraft:spruce_log run setblock ~ ~1 ~ minecraft:stripped_spruce_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_wood"}}] if block ~ ~1 ~ minecraft:spruce_log run setblock ~ ~1 ~ minecraft:spruce_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_fence"}}] if block ~ ~1 ~ minecraft:acacia_wood run setblock ~ ~1 ~ minecraft:acacia_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_fence"}}] if block ~ ~1 ~ minecraft:stripped_acacia_log run setblock ~ ~1 ~ minecraft:acacia_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_fence"}}] if block ~ ~1 ~ minecraft:stripped_acacia_wood run setblock ~ ~1 ~ minecraft:acacia_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_fence"}}] if block ~ ~1 ~ minecraft:birch_wood run setblock ~ ~1 ~ minecraft:birch_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_fence"}}] if block ~ ~1 ~ minecraft:stripped_birch_log run setblock ~ ~1 ~ minecraft:birch_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_fence"}}] if block ~ ~1 ~ minecraft:stripped_birch_wood run setblock ~ ~1 ~ minecraft:birch_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_fence"}}] if block ~ ~1 ~ minecraft:dark_oak_wood run setblock ~ ~1 ~ minecraft:dark_oak_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_fence"}}] if block ~ ~1 ~ minecraft:stripped_dark_oak_log run setblock ~ ~1 ~ minecraft:dark_oak_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_fence"}}] if block ~ ~1 ~ minecraft:stripped_dark_oak_wood run setblock ~ ~1 ~ minecraft:dark_oak_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_fence"}}] if block ~ ~1 ~ minecraft:jungle_wood run setblock ~ ~1 ~ minecraft:jungle_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_fence"}}] if block ~ ~1 ~ minecraft:stripped_jungle_log run setblock ~ ~1 ~ minecraft:jungle_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_fence"}}] if block ~ ~1 ~ minecraft:stripped_jungle_wood run setblock ~ ~1 ~ minecraft:jungle_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_fence"}}] if block ~ ~1 ~ minecraft:oak_wood run setblock ~ ~1 ~ minecraft:oak_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_fence"}}] if block ~ ~1 ~ minecraft:stripped_oak_log run setblock ~ ~1 ~ minecraft:oak_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_fence"}}] if block ~ ~1 ~ minecraft:stripped_oak_wood run setblock ~ ~1 ~ minecraft:oak_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_fence"}}] if block ~ ~1 ~ minecraft:spruce_wood run setblock ~ ~1 ~ minecraft:spruce_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_fence"}}] if block ~ ~1 ~ minecraft:stripped_spruce_log run setblock ~ ~1 ~ minecraft:spruce_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_fence"}}] if block ~ ~1 ~ minecraft:stripped_spruce_wood run setblock ~ ~1 ~ minecraft:spruce_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_fence"}}] if block ~ ~1 ~ minecraft:acacia_planks run setblock ~ ~1 ~ minecraft:acacia_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_fence"}}] if block ~ ~1 ~ minecraft:birch_planks run setblock ~ ~1 ~ minecraft:birch_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_fence"}}] if block ~ ~1 ~ minecraft:dark_oak_planks run setblock ~ ~1 ~ minecraft:dark_oak_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_fence"}}] if block ~ ~1 ~ minecraft:jungle_planks run setblock ~ ~1 ~ minecraft:jungle_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_fence"}}] if block ~ ~1 ~ minecraft:oak_planks run setblock ~ ~1 ~ minecraft:oak_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_fence"}}] if block ~ ~1 ~ minecraft:spruce_planks run setblock ~ ~1 ~ minecraft:spruce_fence replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_planks"}}] if block ~ ~1 ~ minecraft:acacia_wood run setblock ~ ~1 ~ minecraft:acacia_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_planks"}}] if block ~ ~1 ~ minecraft:stripped_acacia_log run setblock ~ ~1 ~ minecraft:acacia_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_planks"}}] if block ~ ~1 ~ minecraft:stripped_acacia_wood run setblock ~ ~1 ~ minecraft:acacia_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_planks"}}] if block ~ ~1 ~ minecraft:birch_wood run setblock ~ ~1 ~ minecraft:birch_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_planks"}}] if block ~ ~1 ~ minecraft:stripped_birch_log run setblock ~ ~1 ~ minecraft:birch_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_planks"}}] if block ~ ~1 ~ minecraft:stripped_birch_wood run setblock ~ ~1 ~ minecraft:birch_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_planks"}}] if block ~ ~1 ~ minecraft:jungle_wood run setblock ~ ~1 ~ minecraft:jungle_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_planks"}}] if block ~ ~1 ~ minecraft:stripped_jungle_log run setblock ~ ~1 ~ minecraft:jungle_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_planks"}}] if block ~ ~1 ~ minecraft:stripped_jungle_wood run setblock ~ ~1 ~ minecraft:jungle_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_planks"}}] if block ~ ~1 ~ minecraft:oak_wood run setblock ~ ~1 ~ minecraft:oak_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_planks"}}] if block ~ ~1 ~ minecraft:stripped_oak_log run setblock ~ ~1 ~ minecraft:oak_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_planks"}}] if block ~ ~1 ~ minecraft:stripped_oak_wood run setblock ~ ~1 ~ minecraft:oak_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_planks"}}] if block ~ ~1 ~ minecraft:spruce_wood run setblock ~ ~1 ~ minecraft:spruce_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_planks"}}] if block ~ ~1 ~ minecraft:stripped_spruce_log run setblock ~ ~1 ~ minecraft:spruce_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_planks"}}] if block ~ ~1 ~ minecraft:stripped_spruce_wood run setblock ~ ~1 ~ minecraft:spruce_planks replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_acacia_log"}}] if block ~ ~1 ~ minecraft:acacia_log run setblock ~ ~1 ~ minecraft:stripped_acacia_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_acacia_wood"}}] if block ~ ~1 ~ minecraft:acacia_log run setblock ~ ~1 ~ minecraft:stripped_acacia_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_acacia_log"}}] if block ~ ~1 ~ minecraft:acacia_wood run setblock ~ ~1 ~ minecraft:stripped_acacia_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_acacia_wood"}}] if block ~ ~1 ~ minecraft:acacia_wood run setblock ~ ~1 ~ minecraft:stripped_acacia_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_birch_log"}}] if block ~ ~1 ~ minecraft:birch_log run setblock ~ ~1 ~ minecraft:stripped_birch_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_birch_wood"}}] if block ~ ~1 ~ minecraft:birch_log run setblock ~ ~1 ~ minecraft:stripped_birch_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_birch_log"}}] if block ~ ~1 ~ minecraft:birch_wood run setblock ~ ~1 ~ minecraft:stripped_birch_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_birch_wood"}}] if block ~ ~1 ~ minecraft:birch_wood run setblock ~ ~1 ~ minecraft:stripped_birch_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_dark_oak_log"}}] if block ~ ~1 ~ minecraft:dark_oak_log run setblock ~ ~1 ~ minecraft:stripped_dark_oak_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_dark_oak_wood"}}] if block ~ ~1 ~ minecraft:dark_oak_log run setblock ~ ~1 ~ minecraft:stripped_dark_oak_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_dark_oak_log"}}] if block ~ ~1 ~ minecraft:dark_oak_wood run setblock ~ ~1 ~ minecraft:stripped_dark_oak_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_dark_oak_wood"}}] if block ~ ~1 ~ minecraft:dark_oak_wood run setblock ~ ~1 ~ minecraft:stripped_dark_oak_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_jungle_log"}}] if block ~ ~1 ~ minecraft:jungle_log run setblock ~ ~1 ~ minecraft:stripped_jungle_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_jungle_wood"}}] if block ~ ~1 ~ minecraft:jungle_log run setblock ~ ~1 ~ minecraft:stripped_jungle_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_jungle_log"}}] if block ~ ~1 ~ minecraft:jungle_wood run setblock ~ ~1 ~ minecraft:stripped_jungle_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_jungle_wood"}}] if block ~ ~1 ~ minecraft:jungle_wood run setblock ~ ~1 ~ minecraft:stripped_jungle_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_oak_log"}}] if block ~ ~1 ~ minecraft:oak_log run setblock ~ ~1 ~ minecraft:stripped_oak_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_oak_wood"}}] if block ~ ~1 ~ minecraft:oak_log run setblock ~ ~1 ~ minecraft:stripped_oak_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_oak_log"}}] if block ~ ~1 ~ minecraft:oak_wood run setblock ~ ~1 ~ minecraft:stripped_oak_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_oak_wood"}}] if block ~ ~1 ~ minecraft:oak_wood run setblock ~ ~1 ~ minecraft:stripped_oak_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_spruce_log"}}] if block ~ ~1 ~ minecraft:spruce_log run setblock ~ ~1 ~ minecraft:stripped_spruce_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_spruce_wood"}}] if block ~ ~1 ~ minecraft:spruce_log run setblock ~ ~1 ~ minecraft:stripped_spruce_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_spruce_log"}}] if block ~ ~1 ~ minecraft:spruce_wood run setblock ~ ~1 ~ minecraft:stripped_spruce_log replace

execute if entity @s[nbt={Item:{id:"minecraft:stripped_spruce_wood"}}] if block ~ ~1 ~ minecraft:spruce_wood run setblock ~ ~1 ~ minecraft:stripped_spruce_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_wood"}}] if block ~ ~1 ~ minecraft:acacia_log run setblock ~ ~1 ~ minecraft:acacia_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:acacia_log"}}] if block ~ ~1 ~ minecraft:acacia_wood run setblock ~ ~1 ~ minecraft:acacia_log replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_wood"}}] if block ~ ~1 ~ minecraft:birch_log run setblock ~ ~1 ~ minecraft:birch_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:birch_log"}}] if block ~ ~1 ~ minecraft:birch_wood run setblock ~ ~1 ~ minecraft:birch_log replace

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_wood"}}] if block ~ ~1 ~ minecraft:dark_oak_log run setblock ~ ~1 ~ minecraft:dark_oak_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:dark_oak_log"}}] if block ~ ~1 ~ minecraft:dark_oak_wood run setblock ~ ~1 ~ minecraft:dark_oak_log replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_wood"}}] if block ~ ~1 ~ minecraft:jungle_log run setblock ~ ~1 ~ minecraft:jungle_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:jungle_log"}}] if block ~ ~1 ~ minecraft:jungle_wood run setblock ~ ~1 ~ minecraft:jungle_log replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_wood"}}] if block ~ ~1 ~ minecraft:oak_log run setblock ~ ~1 ~ minecraft:oak_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:oak_log"}}] if block ~ ~1 ~ minecraft:oak_wood run setblock ~ ~1 ~ minecraft:oak_log replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_wood"}}] if block ~ ~1 ~ minecraft:spruce_log run setblock ~ ~1 ~ minecraft:spruce_wood replace

execute if entity @s[nbt={Item:{id:"minecraft:spruce_log"}}] if block ~ ~1 ~ minecraft:spruce_wood run setblock ~ ~1 ~ minecraft:spruce_log replace
