#######
# Compiled from unnamedde/functions/misc/storage_drawers.mcscript
# to .//data/unnamedde/functions/misc/storage_drawers/craft/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Storage Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Place in a item frame on a\",\"color\":\"green\",\"italic\":false}","{\"text\":\"stripped wood to have\",\"color\":\"green\",\"italic\":false}","{\"text\":\"infinite storage\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701006,unnamedDE:{id:"storage_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 1
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_storage_upgrade
