#######
# Compiled from data/unnamedde/functions/money.mcscript
# to .//data/unnamedde/functions/money/check.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players reset @s check_money
tellraw @s [{"text":"Your balance is: "},{"score":{"name":"@s","objective":"money"},"color":"gold"},{"text":"$","color":"gold"}]
