#######
# Compiled from data/unnamedde/functions/money.mcscript
# to .//data/unnamedde/functions/money/join.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score money ud_settings matches 1.. unless score @s money matches 0.. run scoreboard players operation @s money = #startValue money
execute if score money ud_settings matches 1.. run tellraw @s [{"text":"Your starting balance is: "},{"score":{"name":"@s","objective":"money"},"color":"gold"},{"text":"$","color":"gold"}]

