#######
# Compiled from data/unnamedde/functions/money.mcscript
# to .//data/unnamedde/functions/money/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players enable @a[scores={money=1..}] pay_money
scoreboard players reset @a[scores={money=..0}] pay_money
scoreboard players enable @a check_money
execute as @a[scores={check_money=1..}] run function unnamedde:money/check
execute as @a[scores={pay_money=1..}] at @s if entity @p[distance=.1..] if score @s money >= @s pay_money run function unnamedde:money/pay
execute as @a[scores={pay_money=1..}] at @s if entity @p[distance=.1..] unless score @s money >= @s pay_money run tellraw @s [{"text":"You don't have enough money","color":"dark_red"}]
execute as @a[scores={pay_money=1..}] at @s unless entity @p[distance=.1..] run tellraw @s [{"text":"There's no other player online :(","color":"dark_red"}]
scoreboard players reset @a[scores={pay_money=1..}] pay_money
