#######
# Compiled from data/unnamedde/functions/money.mcscript
# to .//data/unnamedde/functions/money/pay.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players operation @s money -= @s pay_money
scoreboard players operation @p[distance=.1..] money += @s pay_money
playsound minecraft:entity.player.levelup player @p[distance=.1..]
tellraw @s [{"text":"Paid "},{"selector":"@p[distance=.1..]","color":"aqua"},{"text":" "},{"score":{"name":"@s","objective":"pay_money"},"color":"gold"},{"translate":"$","color":"gold"}]
tellraw @p[distance=.1..] [{"text":"You received "},{"score":{"name":"@s","objective":"pay_money"},"color":"gold"},{"text":"$","color":"gold"},{"text":" from "},{"selector":"@s","color":"aqua"}]