#######
# Compiled from unnamedde/functions/misc/death_books.mcscript
# to .//data/unnamedde/functions/misc/death_books/craft_book/2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:advanced_crafter/crafted
tag @s remove ac_lib_advanced_crafter_crafted
tag @s remove ac_lib_advanced_crafter_crafted_death_book
