#######
# Compiled from unnamedde/functions/misc/storage_drawers.mcscript
# to .//data/unnamedde/functions/misc/storage_drawers/input/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @e[type=item,limit=1,sort=nearest] add ud_storage_drawer_checked
execute unless data entity @s Item.tag.unnamedDE.drawer.id run function unnamedde:misc/storage_drawers/set

data modify entity @s Item.tag.unnamedDE.drawer.test.id set from entity @s Item.tag.unnamedDE.drawer.id
data modify entity @s Item.tag.unnamedDE.drawer.test.tag set from entity @s Item.tag.unnamedDE.drawer.tag
execute store success score @s ud_temp run data modify entity @s Item.tag.unnamedDE.drawer.test.id set from entity @e[type=item,limit=1,sort=nearest] Item.id
execute if score @s ud_temp matches 0 store success score @s ud_temp run data modify entity @s Item.tag.unnamedDE.drawer.test.tag set from entity @e[type=item,limit=1,sort=nearest] Item.tag

execute if data entity @s Item.tag.unnamedDE.drawer.tag unless data entity @e[type=item,limit=1,sort=nearest] Item.tag run scoreboard players set @s ud_temp 1

execute if score @s ud_temp matches 0 run function unnamedde:misc/storage_drawers/input/insert

scoreboard players reset @s ud_temp
