#######
# Compiled from unnamedde/functions/misc/storage_drawers.mcscript
# to .//data/unnamedde/functions/misc/storage_drawers/input/insert.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result score @s ud_temp run data get entity @e[type=item,limit=1,sort=nearest] Item.Count
scoreboard players operation @s ud_counter += @s ud_temp
execute store result entity @s Item.tag.unnamedDE.drawer.Count byte 1 run scoreboard players get @s ud_counter
kill @e[type=item,limit=1,sort=nearest,distance=..1]
scoreboard players reset @s ud_temp
