#######
# Compiled from unnamedde/functions/misc/parcour_boots.mcscript
# to .//data/unnamedde/functions/misc/parcour_boots/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
effect clear @a[tag=ud_parcour,nbt=!{Inventory:[{Slot:100b,tag:{unnamedDE:{ParcourEnabled:1}}}]}] jump_boost
effect clear @a[tag=ud_parcour,scores={ud_sneak=1..}] jump_boost
tag @a[nbt=!{Inventory:[{Slot:100b,tag:{unnamedDE:{ParcourEnabled:1}}}]},tag=ud_parcour] remove ud_parcour
tag @a[gamemode=spectator,tag=ud_parcour] remove ud_parcour
tag @a[nbt={OnGround:0b},tag=ud_parcour] remove ud_parcour
tag @a[gamemode=!spectator,nbt={OnGround:1b,Inventory:[{Slot:100b,tag:{unnamedDE:{ParcourEnabled:1}}}]}] add ud_parcour
tag @a[gamemode=!spectator,tag=ud_parcour_jump] add ud_parcour
effect give @a[tag=ud_parcour,nbt=!{ActiveEffects:[{ShowParticles:1b,Id:8b}]}] jump_boost 1 0 true
effect clear @a[tag=ud_parcour,scores={ud_sneak=1..}] jump_boost
execute as @a[tag=ud_parcour,scores={y_rot=90,ud_sneak=1..}] at @s run tag @s add ud_parcour_crouch
execute as @a[tag=ud_parcour_crouch] at @s positioned ~ ~1 ~ unless entity @e[type=shulker,tag=ud_parcour_crouch_shulker,distance=...5] run summon shulker ~ ~ ~ {NoGravity:1b,Silent:1b,Invulnerable:1b,DeathLootTable:"unnamedde:entities/nothing",PersistenceRequired:1b,NoAI:1b,Peek:0b,AttachFace:0b,Tags:["ud_parcour_crouch_shulker"],ActiveEffects:[{Id:14b,Amplifier:0b,Duration:20000000,ShowParticles:0b}]}
execute as @a[tag=ud_parcour_crouch] at @s unless score @s ud_sneak matches 1.. positioned ~ ~1 ~ run function unnamedde:misc/parcour_boots/crouch/deactivate
execute as @a[nbt={Inventory:[{Slot:100b,tag:{unnamedDE:{ParcourEnabled:1}}}]},scores={ud_jump=1..,ud_sneak=1..},tag=!ud_parcour_crouch] at @s anchored eyes unless entity @e[type=shulker,tag=ud_parcour_jump_shulker,distance=...75] unless block ~ ~ ~ #minecraft:slabs unless block ^ ^ ^.5 #unnamedde:nonsolid run tag @s add ud_parcour_jump
execute as @a[nbt={Inventory:[{Slot:100b,tag:{unnamedDE:{ParcourEnabled:1}}}]},scores={ud_jump=1..,ud_sneak=1..},tag=!ud_parcour_crouch] at @s anchored eyes unless entity @e[type=shulker,tag=ud_parcour_jump_shulker,distance=...75] unless block ~ ~ ~ #minecraft:slabs unless block ^ ^ ^.5 #unnamedde:nonsolid run summon shulker ~ ~ ~ {NoGravity:1b,Silent:1b,Invulnerable:1b,DeathLootTable:"unnamedde:entities/nothing",PersistenceRequired:1b,NoAI:1b,Peek:0b,AttachFace:0b,Tags:["ud_parcour_jump_shulker"],ActiveEffects:[{Id:14b,Amplifier:0b,Duration:2000000,ShowParticles:0b}]}
execute as @e[type=shulker,tag=ud_parcour_crouch_shulker] at @s positioned ~ ~-1 ~ unless entity @p[distance=...75,tag=ud_parcour] run tp @s ~ -500 ~
execute as @e[type=shulker,tag=ud_parcour_jump_shulker] at @s unless entity @p[distance=..1.5,nbt={Inventory:[{Slot:100b,tag:{unnamedDE:{ParcourEnabled:1}}}]}] run tp @s ~ -500 ~
