#######
# Compiled from unnamedde/functions/misc/no_placing.mcscript
# to .//data/unnamedde/functions/misc/no_placing/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[gamemode=survival,tag=!ud_NoPlacing,nbt={SelectedItem:{tag:{unnamedDE:{NoPlacing:1}}}}] at @s run function unnamedde:misc/no_placing/no_placing
execute as @a[gamemode=adventure,tag=ud_NoPlacing] at @s unless entity @s[nbt={SelectedItem:{tag:{unnamedDE:{NoPlacing:1}}}}] run function unnamedde:misc/no_placing/placing
