#######
# Compiled from unnamedde/functions/misc/no_placing.mcscript
# to .//data/unnamedde/functions/misc/no_placing/no_placing.mcfunction
#
# Generated by Minecraft Script for 1.13
######
gamemode adventure
tag @s add ud_NoPlacing
