#######
# Compiled from unnamedde/functions/misc/no_placing.mcscript
# to .//data/unnamedde/functions/misc/no_placing/placing.mcfunction
#
# Generated by Minecraft Script for 1.13
######
gamemode survival
tag @s remove ud_NoPlacing