#######
# Compiled from unnamedde/functions/misc/money_additions.mcscript
# to .//data/unnamedde/functions/misc/money_additions/store_money.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s money >= @s store_in_item store result score @s ud_temp run data get entity @s SelectedItem.tag.unnamedDE.storedMoney
execute if score @s money >= @s store_in_item run scoreboard players operation @s ud_temp += @s store_in_item
execute if score @s money >= @s store_in_item store result entity @s SelectedItem.tag.unnamedDE.storedMoney long 1 run scoreboard players get @s ud_temp
execute if score @s money >= @s store_in_item run scoreboard players operation @s money -= @s store_in_item

scoreboard players reset @s ud_temp
scoreboard players reset @s store_in_item
