#######
# Compiled from unnamedde/functions/misc/encrypted_books.mcscript
# to .//data/unnamedde/functions/misc/encrypted_books/clone_text/3.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:air
tag @s remove ac_lib_keep_0
tag @s remove ac_lib_advanced_crafter_crafted
tag @s remove ac_lib_advanced_crafter_crafted_encrypt_book_clone
