#######
# Compiled from unnamedde/functions/misc/tooltips.mcscript
# to .//data/unnamedde/functions/misc/tooltips/notify/clock.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ud_tooltip_clock_notify
advancement grant @s only unnamedde:notify/nighttime
playsound minecraft:block.bell.use master @s ~ ~ ~ 1 1.5