#######
# Compiled from unnamedde/functions/misc/storage_drawers.mcscript
# to .//data/unnamedde/functions/misc/storage_drawers/output/64.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players remove @s ud_counter 64
summon item ^ ^ ^.1 {Tags:["ud_storage_drawer_checked","ud_dummy"],Item:{id:"minecraft:arrow",Count:64b}}
data modify entity @e[type=item,limit=1,sort=nearest,distance=..1.25,tag=ud_dummy] Item.id set from entity @s Item.tag.unnamedDE.drawer.id
data modify entity @e[type=item,limit=1,sort=nearest,distance=..1.25,tag=ud_dummy] Item.tag set from entity @s Item.tag.unnamedDE.drawer.tag
tag @e[type=item,limit=1,sort=nearest,distance=..1.25,tag=ud_dummy] remove ud_dummy
execute store result entity @s Item.tag.unnamedDE.drawer.Count byte 1 run scoreboard players get @s ud_counter
