#######
# Compiled from unnamedde/functions/misc/ender_hoppers.mcscript
# to .//data/unnamedde/functions/misc/ender_hoppers/craft/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:dead_bubble_coral{display:{Name:"{\"text\":\"Ender Upgrade\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Put in a item frame on a hopper to\",\"color\":\"green\",\"italic\":false}","{\"text\":\"enable ender pickup of all items around\",\"color\":\"green\",\"italic\":false}"]},CustomModelData:701005,unnamedDE:{id:"ender_upgrade"},Enchantments:[{id:"enchant",lvl:1s}]} 1
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_ender_upgrade
