#######
# Compiled from unnamedde/functions/misc/start_equip.mcscript
# to .//data/unnamedde/functions/misc/start_equip/equip.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem entity @s armor.head minecraft:leather_helmet
replaceitem entity @s armor.chest minecraft:leather_chestplate
replaceitem entity @s armor.legs minecraft:leather_leggings
replaceitem entity @s armor.feet minecraft:leather_boots
replaceitem entity @s hotbar.0 minecraft:wooden_sword
replaceitem entity @s hotbar.1 minecraft:wooden_pickaxe
replaceitem entity @s hotbar.2 minecraft:wooden_axe
replaceitem entity @s hotbar.3 minecraft:wooden_shovel
replaceitem entity @s hotbar.8 minecraft:bread 32