#######
# Compiled from unnamedde/functions/misc/start_equip.mcscript
# to .//data/unnamedde/functions/misc/start_equip/on_join.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score start_equip ud_options matches 1.. run function unnamedde:misc/start_equip/equip

