#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/fix_slots/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless data block ~ ~ ~ Items[{Slot:0b}].tag.Placeholder if entity @s[tag=!ac_lib_advanced_crafter_trash_can] if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:0b}]} run function ac_lib:advanced_crafter/fix_slots/0
execute unless data block ~ ~ ~ Items[{Slot:0b}].tag.Placeholder if entity @s[tag=!ac_lib_advanced_crafter_trash_can] run replaceitem block ~ ~ ~ container.0 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:4b}].tag.Placeholder if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:4b}]} run function ac_lib:advanced_crafter/fix_slots/4
execute unless data block ~ ~ ~ Items[{Slot:4b}].tag.Placeholder run replaceitem block ~ ~ ~ container.4 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:6b}].tag.Placeholder if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:6b}]} run function ac_lib:advanced_crafter/fix_slots/6
execute unless data block ~ ~ ~ Items[{Slot:6b}].tag.Placeholder run replaceitem block ~ ~ ~ container.6 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:8b}].tag.Placeholder if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:8b}]} run function ac_lib:advanced_crafter/fix_slots/8
execute unless data block ~ ~ ~ Items[{Slot:8b}].tag.Placeholder run replaceitem block ~ ~ ~ container.8 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.Placeholder if entity @s[tag=!ac_lib_advanced_crafter_sink] if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:9b}]} run function ac_lib:advanced_crafter/fix_slots/9
execute unless data block ~ ~ ~ Items[{Slot:9b}].tag.Placeholder if entity @s[tag=!ac_lib_advanced_crafter_sink] run replaceitem block ~ ~ ~ container.9 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:13b}].tag.Placeholder if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:13b}]} run function ac_lib:advanced_crafter/fix_slots/13
execute unless data block ~ ~ ~ Items[{Slot:13b}].tag.Placeholder run replaceitem block ~ ~ ~ container.13 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:15b}].tag.Placeholder if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:15b}]} run function ac_lib:advanced_crafter/fix_slots/15
execute unless data block ~ ~ ~ Items[{Slot:15b}].tag.Placeholder run replaceitem block ~ ~ ~ container.15 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:17b}].tag.Placeholder if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:17b}]} run function ac_lib:advanced_crafter/fix_slots/17
execute unless data block ~ ~ ~ Items[{Slot:17b}].tag.Placeholder run replaceitem block ~ ~ ~ container.17 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:18b}].tag.Placeholder if entity @s[tag=!ac_lib_advanced_crafter_sink] if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:18b}]} run function ac_lib:advanced_crafter/fix_slots/18
execute unless data block ~ ~ ~ Items[{Slot:18b}].tag.Placeholder if entity @s[tag=!ac_lib_advanced_crafter_sink] run replaceitem block ~ ~ ~ container.18 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:22b}].tag.Placeholder if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:22b}]} run function ac_lib:advanced_crafter/fix_slots/22
execute unless data block ~ ~ ~ Items[{Slot:22b}].tag.Placeholder run replaceitem block ~ ~ ~ container.22 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:24b}].tag.Placeholder if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:24b}]} run function ac_lib:advanced_crafter/fix_slots/24
execute unless data block ~ ~ ~ Items[{Slot:24b}].tag.Placeholder run replaceitem block ~ ~ ~ container.24 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute unless data block ~ ~ ~ Items[{Slot:26b}].tag.Placeholder if block ~ ~ ~ minecraft:gray_shulker_box{Items:[{Slot:26b}]} run function ac_lib:advanced_crafter/fix_slots/26
execute unless data block ~ ~ ~ Items[{Slot:26b}].tag.Placeholder run replaceitem block ~ ~ ~ container.26 minecraft:gray_stained_glass_pane{Placeholder: 1, display: {Name: '{"text":" "}'}}

execute if block ~ ~-1 ~ minecraft:hopper{Items:[{Slot:0b,tag:{Placeholder:1}}]} run replaceitem block ~ ~-1 ~ container.0 air

execute if block ~ ~-1 ~ minecraft:hopper{Items:[{Slot:1b,tag:{Placeholder:1}}]} run replaceitem block ~ ~-1 ~ container.1 air

execute if block ~ ~-1 ~ minecraft:hopper{Items:[{Slot:2b,tag:{Placeholder:1}}]} run replaceitem block ~ ~-1 ~ container.2 air

execute if block ~ ~-1 ~ minecraft:hopper{Items:[{Slot:3b,tag:{Placeholder:1}}]} run replaceitem block ~ ~-1 ~ container.3 air

execute if block ~ ~-1 ~ minecraft:hopper{Items:[{Slot:4b,tag:{Placeholder:1}}]} run replaceitem block ~ ~-1 ~ container.4 air

