#######
# Compiled from data/unnamedde/functions/player_id.mcscript
# to .//data/unnamedde/functions/player_id/deny_invite.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a if score @s player_id = @p invite_id run tellraw @s [{"selector":"@p","color":"aqua"},{"text":" denied your invite", "color":"dark_red"}]
scoreboard players reset @s invite_id
tellraw @s [{"text":"Denied Invite", "color":"dark_red"}]
