#######
# Compiled from data/unnamedde/functions/player_id.mcscript
# to .//data/unnamedde/functions/player_id/first_join.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a if score @s player_id = @s group_id run scoreboard players enable @s kick_player
execute as @a if score @s player_id = @s group_id run scoreboard players enable @s invite_player
execute as @a if score @s player_id = @s group_id run scoreboard players reset @s[scores={leave_group=0}] leave_group
execute as @a unless score @s player_id = @s group_id run scoreboard players reset @s[scores={kick_player=0}] kick_player
execute as @a unless score @s player_id = @s group_id run scoreboard players reset @s[scores={invite_player=0}] invite_player
execute as @a unless score @s player_id = @s group_id run scoreboard players enable @s leave_group
tag @s add ud_id_set
scoreboard players add #count player_id 1
scoreboard players operation @s player_id = #count player_id
scoreboard players operation @s group_id = @s player_id
function #unnamedde:on_first_join
execute if score @s player_id matches 1 run tellraw @s ""
execute if score @s player_id matches 1 run function #unnamedde:on_first_player_join

