#######
# Compiled from data/unnamedde/functions/player_id.mcscript
# to .//data/unnamedde/functions/player_id/invite.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players operation @p[distance=.1..] invite_id = @s group_id
scoreboard players enable @p[distance=.1..] accept_invite
tellraw @s [{"text":"Invited "},{"selector":"@p[distance=.1..]","color":"aqua"},{"text":" to your group"}]
tellraw @p[distance=.1..] [{"text":"You were invited by "},{"selector":"@s","color":"aqua"},{"text":" to his group"}]
execute as @p[distance=.1..] at @s run tellraw @s [{"text":"[Accept]","color":"dark_green","hoverEvent":{"action":"show_text","value":"Click to accept"},"clickEvent":{"action":"run_command","value":"/trigger accept_invite set 1"}},{"text":" "},{"text":"[Deny]","color":"dark_red","hoverEvent":{"action":"show_text","value":"Click to deny"},"clickEvent":{"action":"run_command","value":"/trigger accept_invite set 2"}}]
