#######
# Compiled from data/unnamedde/functions/player_id.mcscript
# to .//data/unnamedde/functions/player_id/join.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players reset @s accept_invite
