#######
# Compiled from data/unnamedde/functions/player_id.mcscript
# to .//data/unnamedde/functions/player_id/leave.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s group_id = @s player_id run tellraw @s [{"text":"You can't leave your own group", "color":"dark_red"}]
execute unless score @s group_id = @s player_id run tellraw @s [{"text":"Left your group", "color":"dark_red"}]
execute unless score @s group_id = @s player_id as @a[distance=.1..] if score @s group_id = @p group_id run tellraw @s [{"selector":"@p","color":"aqua"},{"text":" left your group", "color":"dark_red"}]
execute unless score @s group_id = @s player_id run scoreboard players operation @s group_id = @s player_id
scoreboard players reset @s leave_group
