#######
# Compiled from data/unnamedde/functions/player_id.mcscript
# to .//data/unnamedde/functions/player_id/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[scores={invite_player=1..}] at @s if score @s group_id = @s player_id run function unnamedde:player_id/invite
execute as @a[scores={invite_player=1..}] at @s run scoreboard players reset @s invite_player
execute as @a[scores={accept_invite=1}] at @s if score @s invite_id matches 1.. run function unnamedde:player_id/accept_invite
execute as @a[scores={accept_invite=1}] at @s run scoreboard players reset @s accept_invite
execute as @a[scores={accept_invite=2}] at @s if score @s invite_id matches 1.. run function unnamedde:player_id/deny_invite
execute as @a[scores={accept_invite=2}] at @s run scoreboard players reset @s accept_invite
execute as @a[scores={leave_group=1..}] at @s run function unnamedde:player_id/leave
execute as @a[scores={kick_player=1..}] at @s if score @s group_id = @s player_id run function unnamedde:player_id/kick
execute as @a[scores={kick_player=1..}] at @s run scoreboard players reset @s kick_player
execute as @a at @s at @a[distance=.1..20] if score @p group_id = @s group_id run function unnamedde:player_id/visuals
