#######
# Compiled from data/unnamedde/functions/player_id.mcscript
# to .//data/unnamedde/functions/player_id/visuals.mcfunction
#
# Generated by Minecraft Script for 1.13
######
particle minecraft:dust 0 1 0 1 ~ ~1 ~ .25 .4 .25 .5 1 normal @s
