#######
# Compiled from unnamedde/functions/misc/storage_drawers.mcscript
# to .//data/unnamedde/functions/misc/storage_drawers/check.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s [{"score":{"name":"@e[tag=ud_storage_drawer,type=item_frame,limit=1,sort=nearest]","objective":"ud_counter"},"color":"green"},{"text":"x \"","color":"blue"},{"nbt":"Item.tag.unnamedDE.drawer.id","entity":"@e[tag=ud_storage_drawer,type=item_frame,limit=1,sort=nearest]","color":"green"},{"text":"\" stored (","color":"blue"},{"nbt":"Item.tag.unnamedDE.drawer.tag","entity":"@e[tag=ud_storage_drawer,type=item_frame,limit=1,sort=nearest]","color":"green"},{"text":")","color":"blue"}]
