#######
# Compiled from unnamedde/functions/misc/storage_drawers.mcscript
# to .//data/unnamedde/functions/misc/storage_drawers/init.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add ud_storage_drawer
scoreboard players set @s ud_counter 0
execute if data entity @s Item.tag.unnamedDE.drawer.Count store result score @s ud_counter run data get entity @s Item.tag.unnamedDE.drawer.Count

