#######
# Compiled from unnamedde/functions/misc/storage_drawers.mcscript
# to .//data/unnamedde/functions/misc/storage_drawers/main_.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[distance=..5] at @s run scoreboard players enable @s check_drawer
execute if entity @s[tag=!ud_storage_drawer] run function unnamedde:misc/storage_drawers/init

execute unless data entity @s Item.tag.unnamedDE.drawer.id align xyz run particle dust 0 1 0 1 ~.5 ~.5 ~.5 .4 .4 .4 .1 1

execute align xyz positioned ~.5 ~.5 ~.5 if entity @e[type=item,limit=1,sort=random,distance=..1,tag=!ud_storage_drawer_checked] run function unnamedde:misc/storage_drawers/input/detect
execute if entity @s[nbt={ItemRotation:1b}] run function unnamedde:misc/storage_drawers/output/64_check

execute if entity @s[nbt={ItemRotation:7b}] run function unnamedde:misc/storage_drawers/output/1_check

execute if score @s ud_itfr_rotation matches 2..6 run data modify entity @s ItemRotation set value 0b

