#######
# Compiled from unnamedde/functions/misc/storage_drawers.mcscript
# to .//data/unnamedde/functions/misc/storage_drawers/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=ud_storage_drawer,type=item_frame] at @s unless entity @s[nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] run function unnamedde:misc/storage_drawers/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:4b}] positioned ~1 ~ ~ if block ~ ~ ~ #unnamed_core:stripped_wood run function unnamedde:misc/storage_drawers/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:4b}] positioned ~1 ~ ~ unless block ~ ~ ~ #unnamed_core:stripped_wood if entity @s[tag=ud_storage_drawer] run function unnamedde:misc/storage_drawers/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:5b}] positioned ~-1 ~ ~ if block ~ ~ ~ #unnamed_core:stripped_wood run function unnamedde:misc/storage_drawers/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:5b}] positioned ~-1 ~ ~ unless block ~ ~ ~ #unnamed_core:stripped_wood if entity @s[tag=ud_storage_drawer] run function unnamedde:misc/storage_drawers/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:3b}] positioned ~ ~ ~-1 if block ~ ~ ~ #unnamed_core:stripped_wood run function unnamedde:misc/storage_drawers/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:3b}] positioned ~ ~ ~-1 unless block ~ ~ ~ #unnamed_core:stripped_wood if entity @s[tag=ud_storage_drawer] run function unnamedde:misc/storage_drawers/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:2b}] positioned ~ ~ ~1 if block ~ ~ ~ #unnamed_core:stripped_wood run function unnamedde:misc/storage_drawers/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:2b}] positioned ~ ~ ~1 unless block ~ ~ ~ #unnamed_core:stripped_wood if entity @s[tag=ud_storage_drawer] run function unnamedde:misc/storage_drawers/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:1b}] positioned ~ ~-1 ~ if block ~ ~ ~ #unnamed_core:stripped_wood run function unnamedde:misc/storage_drawers/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:1b}] positioned ~ ~-1 ~ unless block ~ ~ ~ #unnamed_core:stripped_wood if entity @s[tag=ud_storage_drawer] run function unnamedde:misc/storage_drawers/remove
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:0b}] positioned ~ ~1 ~ if block ~ ~ ~ #unnamed_core:stripped_wood run function unnamedde:misc/storage_drawers/main_
execute as @e[type=item_frame,nbt={Item:{tag:{unnamedDE:{id:"storage_upgrade"}}}}] at @s if entity @s[nbt={Facing:0b}] positioned ~ ~1 ~ unless block ~ ~ ~ #unnamed_core:stripped_wood if entity @s[tag=ud_storage_drawer] run function unnamedde:misc/storage_drawers/remove
execute as @a[scores={check_drawer=0}] at @s unless entity @e[tag=ud_storage_drawer,type=item_frame,distance=..5] run scoreboard players reset @s check_drawer
execute as @a[scores={check_drawer=1}] at @s if entity @e[tag=ud_storage_drawer,type=item_frame,distance=..5] if data entity @e[tag=ud_storage_drawer,type=item_frame,limit=1,sort=nearest] Item.tag.unnamedDE.drawer.id run function unnamedde:misc/storage_drawers/check
scoreboard players reset @a[scores={check_drawer=1..}] check_drawer
scoreboard players reset @a[scores={check_drawer=..-1}] check_drawer
