#######
# Compiled from unnamedde/functions/misc/storage_drawers.mcscript
# to .//data/unnamedde/functions/misc/storage_drawers/main_check.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score storage_drawers ud_options matches 1.. run function unnamedde:misc/storage_drawers/main

