#######
# Compiled from unnamedde/functions/misc/storage_drawers.mcscript
# to .//data/unnamedde/functions/misc/storage_drawers/remove.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove ud_storage_drawer
scoreboard players reset @s ud_counter
