#######
# Compiled from unnamedde/functions/misc/trash_can.mcscript
# to .//data/unnamedde/functions/misc/trash_can/craft.mcfunction
#
# Generated by Minecraft Script for 1.13
######
advancement revoke @s only unnamedde:craft_trash_can_utility
recipe take @s unnamedde:trash_can
clear @s minecraft:structure_void 1
scoreboard players set @s kc_c_menu_m 15
