#######
# Compiled from unnamedde/functions/misc/trash_can.mcscript
# to .//data/unnamedde/functions/misc/trash_can/destroy.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=armor_stand,tag=!ud_trash_can_init,tag=ud_trash_can] at @s if block ~ ~ ~ air run data merge entity @e[limit=1,sort=nearest,type=item,nbt={Item:{id:"minecraft:hopper",Count:1b}}] {Item:{id:"minecraft:armor_stand",Count:1b,tag:{CustomModelData:705104,unnamedDE:{id:"trash_can_place"},display:{Name:"{\"translate\":\"Trashcan\",\"italic\":\"false\"}",Lore:["{\"translate\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"]},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["ud_trash_can","ud_trash_can_init"]}}}}
execute as @e[type=armor_stand,tag=!ud_trash_can_init,tag=ud_trash_can] at @s if block ~ ~ ~ air run kill @s
