#######
# Compiled from unnamedde/functions/misc/trash_can.mcscript
# to .//data/unnamedde/functions/misc/trash_can/functionality_block.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:3b}]} run replaceitem block ~ ~ ~ container.4 arrow
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:3b}]} run data modify block ~ ~ ~ Items[{Slot:4b}].id set from block ~ ~ ~ Items[{Slot:3b}].id
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:3b}]} run data modify block ~ ~ ~ Items[{Slot:4b}].Count set from block ~ ~ ~ Items[{Slot:3b}].Count
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:3b}]} run data modify block ~ ~ ~ Items[{Slot:4b}].tag set from block ~ ~ ~ Items[{Slot:3b}].tag
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:3b}]} run replaceitem block ~ ~ ~ container.3 air

execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:2b}]} run replaceitem block ~ ~ ~ container.3 arrow
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:2b}]} run data modify block ~ ~ ~ Items[{Slot:3b}].id set from block ~ ~ ~ Items[{Slot:2b}].id
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:2b}]} run data modify block ~ ~ ~ Items[{Slot:3b}].Count set from block ~ ~ ~ Items[{Slot:2b}].Count
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:2b}]} run data modify block ~ ~ ~ Items[{Slot:3b}].tag set from block ~ ~ ~ Items[{Slot:2b}].tag
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:2b}]} run replaceitem block ~ ~ ~ container.2 air

execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:1b}]} run replaceitem block ~ ~ ~ container.2 arrow
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:1b}]} run data modify block ~ ~ ~ Items[{Slot:2b}].id set from block ~ ~ ~ Items[{Slot:1b}].id
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:1b}]} run data modify block ~ ~ ~ Items[{Slot:2b}].Count set from block ~ ~ ~ Items[{Slot:1b}].Count
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:1b}]} run data modify block ~ ~ ~ Items[{Slot:2b}].tag set from block ~ ~ ~ Items[{Slot:1b}].tag
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:1b}]} run replaceitem block ~ ~ ~ container.1 air

execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:0b}]} run replaceitem block ~ ~ ~ container.1 arrow
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:0b}]} run data modify block ~ ~ ~ Items[{Slot:1b}].id set from block ~ ~ ~ Items[{Slot:0b}].id
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:0b}]} run data modify block ~ ~ ~ Items[{Slot:1b}].Count set from block ~ ~ ~ Items[{Slot:0b}].Count
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:0b}]} run data modify block ~ ~ ~ Items[{Slot:1b}].tag set from block ~ ~ ~ Items[{Slot:0b}].tag
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:0b}]} run replaceitem block ~ ~ ~ container.0 air

