#######
# Compiled from unnamedde/functions/misc/trash_can.mcscript
# to .//data/unnamedde/functions/misc/trash_can/functionality_detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ minecraft:hopper{Items:[{Slot:0b}]} run function unnamedde:misc/trash_can/functionality_block

execute as @e[type=item,distance=..1,nbt={OnGround:1b}] run function unnamedde:misc/trash_can/functionality_item
