#######
# Compiled from unnamedde/functions/misc/trash_can.mcscript
# to .//data/unnamedde/functions/misc/trash_can/maintain.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data merge block ~ ~ ~ {TransferCooldown:1000000}
execute if block ~ ~-1 ~ minecraft:magma_block run replaceitem block ~ ~ ~ container.0 air
execute if block ~ ~-1 ~ minecraft:lava run replaceitem block ~ ~ ~ container.0 air
execute if block ~ ~-1 ~ minecraft:magma_block run replaceitem block ~ ~ ~ container.1 air
execute if block ~ ~-1 ~ minecraft:lava run replaceitem block ~ ~ ~ container.1 air
execute if block ~ ~-1 ~ minecraft:magma_block run replaceitem block ~ ~ ~ container.2 air
execute if block ~ ~-1 ~ minecraft:lava run replaceitem block ~ ~ ~ container.2 air
execute if block ~ ~-1 ~ minecraft:magma_block run replaceitem block ~ ~ ~ container.3 air
execute if block ~ ~-1 ~ minecraft:lava run replaceitem block ~ ~ ~ container.3 air
execute if block ~ ~-1 ~ minecraft:magma_block run replaceitem block ~ ~ ~ container.4 air
execute if block ~ ~-1 ~ minecraft:lava run replaceitem block ~ ~ ~ container.4 air

