#######
# Compiled from unnamedde/functions/misc/trash_can.mcscript
# to .//data/unnamedde/functions/misc/trash_can/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function unnamedde:misc/trash_can/place/detect
function unnamedde:misc/trash_can/destroy
execute as @e[type=armor_stand,tag=ud_trash_can] at @s run function unnamedde:misc/trash_can/maintain
execute as @e[type=armor_stand,tag=ud_trash_can] at @s run function unnamedde:misc/trash_can/functionality_detect
