#######
# Compiled from unnamedde/functions/misc/plated_elytras.mcscript
# to .//data/unnamedde/functions/misc/plated_elytras/craft/diamond/2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:advanced_crafter/crafted
tag @s remove ac_lib_advanced_crafter_crafted
tag @s remove ac_lib_advanced_crafter_crafted_diamond_elytra
