#######
# Compiled from unnamedde/functions/misc/silencer.mcscript
# to .//data/unnamedde/functions/misc/silencer/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=!player,name="silence me",tag=!silenced] run function unnamedde:misc/silencer/silence
execute as @e[type=!player,name=!silenced,tag=silenced] run function unnamedde:misc/silencer/unsilence
