#######
# Compiled from unnamedde/functions/misc/silencer.mcscript
# to .//data/unnamedde/functions/misc/silencer/silence.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add silenced
data merge entity @s {Silent:1b,CustomName:"{\"text\":\"silenced\",\"color\":\"dark_gray\"}"}
