#######
# Compiled from unnamedde/functions/misc/silencer.mcscript
# to .//data/unnamedde/functions/misc/silencer/unsilence.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove silenced
data merge entity @s {Silent:0b}