#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/craft.mcfunction
#
# Generated by Minecraft Script for 1.13
######
advancement revoke @s only ac_lib:craft_advanced_crafter_utility
recipe take @s ac_lib:advanced_crafter
clear @s minecraft:structure_void 1
scoreboard players set @s ud_creative_menu 11
