#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/destroy.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=armor_stand,tag=!ac_lib_advanced_crafter_init,tag=ac_lib_advanced_crafter] at @s if block ~ ~ ~ air run function ac_lib:advanced_crafter/drop_items/main
execute as @e[type=armor_stand,tag=!ac_lib_advanced_crafter_init,tag=ac_lib_advanced_crafter] at @s if block ~ ~ ~ air run data remove entity @e[limit=1,sort=nearest,type=item,nbt={Item:{id:"minecraft:gray_shulker_box",Count:1b}}] Item.tag.BlockEntityTag
execute as @e[type=armor_stand,tag=!ac_lib_advanced_crafter_init,tag=ac_lib_advanced_crafter] at @s if block ~ ~ ~ air run data merge entity @e[limit=1,sort=nearest,type=item,nbt={Item:{id:"minecraft:gray_shulker_box",Count:1b}}] {Item:{id:"minecraft:armor_stand",Count:1b,tag:{display:{Name:"{\"text\":\"Advanced Crafter\",\"italic\":false}",Lore:["{\"translate\":\"Right-click to place\",\"color\":\"dark_green\",\"italic\":false}"]},CustomModelData:701001,ac_lib:{id:"advanced_crafter"},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["ac_lib_advanced_crafter","ac_lib_advanced_crafter_init"],DisabledSlots:4144959}}}}
execute as @e[type=armor_stand,tag=!ac_lib_advanced_crafter_init,tag=ac_lib_advanced_crafter] at @s if block ~ ~ ~ air run kill @s
