#######
# Compiled from data/ac_lib/functions/advanced_crafter.mcscript
# to .//data/ac_lib/functions/advanced_crafter/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:advanced_crafter/place/detect
execute as @e[tag=ac_lib_advanced_crafter] at @s run function #ac_lib:advanced_crafter_recipes
execute as @e[tag=ac_lib_advanced_crafter] at @s run function ac_lib:advanced_crafter/fix_slots/main
function ac_lib:advanced_crafter/destroy
