#######
# Compiled from unnamedde/functions/misc/greeting.mcscript
# to .//data/unnamedde/functions/misc/admin_greeting.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s [{"text":"You are the first player joining this server! To change the starting balance run ","color":"blue"},{"text":"/scoreboard players set #startValue money ","color":"white"},{"text":"AMOUNT","color":"gray","italic":true},{"text":". To change your own balance run ","color":"blue"},{"text":"/scoreboard players set @s money ","color":"white"},{"text":"AMOUNT","color":"gray","italic":true},{"text":".","color":"blue"}]