#######
# Compiled from unnamedde/functions/misc/concrete_in_water.mcscript
# to .//data/unnamedde/functions/misc/concrete_in_water.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=item,nbt={Item:{id:"minecraft:white_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:white_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:orange_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:orange_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:magenta_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:magenta_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:light_blue_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:light_blue_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:yellow_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:yellow_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:lime_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:lime_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:pink_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:pink_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:gray_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:gray_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:light_gray_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:light_gray_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:cyan_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:cyan_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:purple_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:purple_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:blue_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:blue_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:brown_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:brown_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:green_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:green_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:red_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:red_concrete"
execute as @e[type=item,nbt={Item:{id:"minecraft:black_concrete_powder"}}] at @s if block ~ ~ ~ minecraft:water run data modify entity @s Item.id set value "minecraft:black_concrete"