#######
# Compiled from unnamedde/functions/misc/dimension_notifications.mcscript
# to .//data/unnamedde/functions/misc/dimension_notifications.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a at @s if entity @s[nbt={Dimension:0}] unless score @s dim matches 0 run tellraw @s [{"text":"You entered the overworld","color":"yellow"}]
execute as @a at @s if entity @s[nbt={Dimension:0}] unless score @s dim matches 0 run tellraw @a[nbt={Dimension:0},distance=.1..] [{"selector":"@s","color":"aqua"},{"text":" entered the overworld","color":"yellow"}]
execute as @a at @s if entity @s[nbt={Dimension:0}] unless score @s dim matches 0 if score @s dim matches -1 run tellraw @a[nbt={Dimension:-1}] [{"selector":"@s","color":"aqua"},{"text":" left the nether","color":"yellow"}]
execute as @a at @s if entity @s[nbt={Dimension:0}] unless score @s dim matches 0 if score @s dim matches 1 run tellraw @a[nbt={Dimension:1}] [{"selector":"@s","color":"aqua"},{"text":" left the end","color":"yellow"}]
execute as @a at @s if entity @s[nbt={Dimension:-1}] unless score @s dim matches -1 run tellraw @s [{"text":"You entered the nether","color":"yellow"}]
execute as @a at @s if entity @s[nbt={Dimension:-1}] unless score @s dim matches -1 run tellraw @a[nbt={Dimension:-1},distance=.1..] [{"selector":"@s","color":"aqua"},{"text":" entered the nether","color":"yellow"}]
execute as @a at @s if entity @s[nbt={Dimension:-1}] unless score @s dim matches -1 if score @s dim matches 0 run tellraw @a[nbt={Dimension:0}] [{"selector":"@s","color":"aqua"},{"text":" left the overworld","color":"yellow"}]
execute as @a at @s if entity @s[nbt={Dimension:-1}] unless score @s dim matches -1 if score @s dim matches 1 run tellraw @a[nbt={Dimension:1}] [{"selector":"@s","color":"aqua"},{"text":" left the end","color":"yellow"}]
execute as @a at @s if entity @s[nbt={Dimension:1}] unless score @s dim matches 1 run tellraw @s [{"text":"You entered the end","color":"yellow"}]
execute as @a at @s if entity @s[nbt={Dimension:1}] unless score @s dim matches 1 run tellraw @a[nbt={Dimension:1},distance=.1..] [{"selector":"@s","color":"aqua"},{"text":" entered the end","color":"yellow"}]
execute as @a at @s if entity @s[nbt={Dimension:1}] unless score @s dim matches 1 if score @s dim matches -1 run tellraw @a[nbt={Dimension:-1}] [{"selector":"@s","color":"aqua"},{"text":" left the nether","color":"yellow"}]
execute as @a at @s if entity @s[nbt={Dimension:1}] unless score @s dim matches 1 if score @s dim matches 0 run tellraw @a[nbt={Dimension:0}] [{"selector":"@s","color":"aqua"},{"text":" left the overworld","color":"yellow"}]