#######
# Compiled from unnamedde/functions/misc/greeting.mcscript
# to .//data/unnamedde/functions/misc/greeting.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s {"text":"Welcome to the server!","color":"yellow"}
