#######
# Compiled from unnamedde/functions/misc/hopper_minecarts.mcscript
# to .//data/unnamedde/functions/misc/hopper_minecarts.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a at @s as @e[type=hopper_minecart,distance=..20,nbt={Enabled:0b}] at @s run particle minecraft:dust 1 0 0 1 ~ ~.2 ~ .25 .2 .25 1 1