#######
# Compiled from unnamedde/functions/misc/no_too_expensive.mcscript
# to .//data/unnamedde/functions/misc/no_too_expensive.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if data entity @s Inventory[{Slot:0b}].tag.RepairCost run data remove entity @s Inventory[{Slot:0b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:1b}].tag.RepairCost run data remove entity @s Inventory[{Slot:1b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:2b}].tag.RepairCost run data remove entity @s Inventory[{Slot:2b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:3b}].tag.RepairCost run data remove entity @s Inventory[{Slot:3b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:4b}].tag.RepairCost run data remove entity @s Inventory[{Slot:4b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:5b}].tag.RepairCost run data remove entity @s Inventory[{Slot:5b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:6b}].tag.RepairCost run data remove entity @s Inventory[{Slot:6b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:7b}].tag.RepairCost run data remove entity @s Inventory[{Slot:7b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:8b}].tag.RepairCost run data remove entity @s Inventory[{Slot:8b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:9b}].tag.RepairCost run data remove entity @s Inventory[{Slot:9b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:10b}].tag.RepairCost run data remove entity @s Inventory[{Slot:10b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:11b}].tag.RepairCost run data remove entity @s Inventory[{Slot:11b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:12b}].tag.RepairCost run data remove entity @s Inventory[{Slot:12b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:13b}].tag.RepairCost run data remove entity @s Inventory[{Slot:13b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:14b}].tag.RepairCost run data remove entity @s Inventory[{Slot:14b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:15b}].tag.RepairCost run data remove entity @s Inventory[{Slot:15b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:16b}].tag.RepairCost run data remove entity @s Inventory[{Slot:16b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:17b}].tag.RepairCost run data remove entity @s Inventory[{Slot:17b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:18b}].tag.RepairCost run data remove entity @s Inventory[{Slot:18b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:19b}].tag.RepairCost run data remove entity @s Inventory[{Slot:19b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:20b}].tag.RepairCost run data remove entity @s Inventory[{Slot:20b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:21b}].tag.RepairCost run data remove entity @s Inventory[{Slot:21b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:22b}].tag.RepairCost run data remove entity @s Inventory[{Slot:22b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:23b}].tag.RepairCost run data remove entity @s Inventory[{Slot:23b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:24b}].tag.RepairCost run data remove entity @s Inventory[{Slot:24b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:25b}].tag.RepairCost run data remove entity @s Inventory[{Slot:25b}].tag.RepairCost

execute if data entity @s Inventory[{Slot:26b}].tag.RepairCost run data remove entity @s Inventory[{Slot:26b}].tag.RepairCost
